---
title: 启程赫尔辛基
author: "Hongyang Zhou"
date: "2020-11-05"
categories: [travel]
---

欧洲人习惯的月日记法和中国一致，但是和美国是反的，估计单这就能闹出不少乱子。咱既然来了欧洲，当然也要入乡随俗了。

这趟从纽约飞往赫尔辛基的旅程本身四平八稳，但前前后后的经过却是起伏跌宕。在疫情与通航禁令下摸着石头过大西洋，也是一段难得的经历。

## 回溯

一切都要追溯回2020年的4月份。彼时国内疫情封城禁航了2个月，终于得到了控制，而国外的疫情则逐渐抬头。来往全球的航班把病毒带到了世界各地，后知后觉的政府和民众光顾着看中国热闹，等到病毒真来了的时候早就来不及了。为什么2003年SARS时候数字远不如新冠夸张？还是回归数字说话。现在的一些数据表明SARS全球总确诊数目8098例，致死率大致在15%左右。这里的可怕点在于综合15%的高致死率，或者是高于50%的65岁以上致死率。所以当医学上确认这些数字后，即便是没有流行病经验的行政当局也会全力以赴控制疫情。而2020年的新冠，最开始在武汉致死率一度达到了20%，因为并不了解这到底是什么病，只知道症状和当年的SARS很像，传染性更强，并引发了国内尤其是湖北地区的社会性恐慌。而9个月过后，到目前为止新冠全球范围内的致死率在2%左右。作为对比，流感一般的致死率在0.1%附近，比新冠低一个量级，这也是为啥新冠常被成为大号流感的原因。另外一个需要知道的重要数字是传染率，被定义为平均一个患者能感染多少健康人，英文代号R0 value（参阅[维基](https://en.wikipedia.org/wiki/Basic_reproduction_number)）。显然这个数字不是一个直接能够得到的量，而是一个导出量，所以各家的统计方法得出的结果会有明显区别。目前我看到的数字，新冠的R0值从1.1到6不等，平均可能在2.5左右。当年的SARS呢，则是在0.19到1.08之间。这些数字意味着什么呢？可能从直觉上人们会觉得1和2很接近，但这是不对的。问题出在，传染病的数学模型里面，总是会带有指数函数，而这个1、2的数字，实际上代表的指数项的系数。回头看自中学数学里开始接触的指数以后，你便会意识到这其实是巨大的区别。所以简单来说衡量传染病的基本要素就是两个指标：致死率和传染率。但显然世界范围内众多的政府官员都不能真正理解这些数字的来源和意义，单纯的文科逻辑治国显然是意识不到很多问题的危险程度。比如说，建立在这两个量之上，现在你再归纳出一个新的量用来衡量一种传染病究竟需要什么程度的控制和干预吗？我也尚不知道答案，但显然这是任何决策的出发点。如果不讲究科学，政策都会变成拍脑袋的娱乐，就像现实中发生的，很多国家和地方的措施和政策都走向了荒谬的方向。科学不是说目前的模型就是对的，而是说，基于当前的理性认知，我们能不能做出利益最大化的选择。这次的疫情，正是一个检验全球领袖和民众科学素养的试炼场：没有任何人能够对客观事物真正全面地了解，但是我们依然可以做出出于逻辑和理性的判断。

总之，当我四月份开始申请芬兰签证时，所有的签证申请都戛然而止了。本来我计划五月份答辩，六月份就奔赴赫尔辛基，一下子全都要打乱重来。日子一晃过得很快，大概六月初修改完文章，月底了结博士期间的所有活儿，七月八月悠哉地过日子折腾点儿代码整理些笔记玩儿游戏跟师兄师姐出游，九月开始实践之前反思中想到的提升模拟效果的方案以及GPU并行化的尝试，十月份有了半成品的OpenACC实现和新模型的结果，并且完成了部分工作的过渡。期间我在密歇根的研究生宿舍白住了两个月，直到八月底被“踢出”宿舍卷铺盖儿来到纽约，中途还在匹兹堡转了一圈儿并享受了回市中心希尔顿的夜晚。九月初通过多方途径得知又可以办理签证了，于是立即联系预约到了月底的面签。之前耽搁了一些是由于一直搞错了领馆和旅游商务签证代理中心的关系，直到直接询问领事馆才明白我不需要通过代理操作。芬兰的纽约领馆在4大道37街的一栋写字楼里，从李堡出发大概一小时，整个面前过程非常顺利，因为实际上也没人在办理签证。面签之后三天，外交部还有人专门发来问询函确认我时间填写错误的问题，回复后立马给了居住证。之后便开始在网上订公寓并确定机票行程，反复比对后发现一开始看见的廉价机票纯属子虚乌有，实际上航线根本没有恢复，但航空公司依旧在销售机票。无奈之下只好选择了汉莎航空经法兰克福到赫尔辛基的15小时行程，一共花了近3000刀，肉疼得不行。芬兰这边的老师知道后很快告诉我愿意帮我报销一部分机票，也是令我喜出望外。

如今看来这几个月的“空闲”也是福祸参半。我少挣了几个月的工资，又在财富自由上落后了一节；我晚开始了博后的工作，说不定就错过了些出成果的时间；我有了更多的时间完成毕业论文，算是对过去五年一个完整的交代；我有了更多的时间和朋友聊天，人生也多了相伴而行的动力；我有幸和舅舅一家一起生活了两个月，异国他乡的亲人相聚可不容易。我没有埋怨生活的理由，无论好坏。

## 航程

纽约的JFK机场及其空旷，或者说我从没见过这么清闲的机场。整架飞机一共就20名乘客10名空乘飞行员，头一次能体验到在飞机上躺下来的姿势。法兰克福当地时间凌晨5点降落，通过了进欧盟的审查，但由于最终目的地是芬兰换乘所以就是例行公事地看看，很快就过了关从A登机口到了B登机口。中间连接带有一条200米的长廊，一度空留我一人在踱步，每一次的脚步声都异常清楚，就差个月亮和我对影成三人了。在新登机口等候了5个小时，期间差一点昏睡过去。一早上就有一个英文不好的伊斯兰小姐姐过来跟我确认航班，也是转机且人生地不熟吧。法兰克福到赫尔辛基的航班竟然是满员，大大出乎我意料之外；在2小时的航班上结结实实地睡了一觉，掐指一算，这个距离也等同于深圳到合肥、武汉和上海，欧洲一国等同于中国一省，此言不虚。落地后入关倒是意料之外地漫长，等了将近40分钟，结果轮到我递上居住证和护照，啥都不问就进来了。像我这种从“危险”国家过来的要求进行10天的自我隔离，在机场也不能搭乘公共交通，所以只好选择出租：结果还没到大量出租的等候口时就被一名小哥截了胡，用一辆宝马拉走了。我意识不太清醒，只是隐隐觉得这做派和说辞颇像国内机场的黑车，不到正常等候的地方反倒是在出口处提前下手，各种游说无非是说他们是个公司正规且便宜。我事先查过Uber的价格，司机的报价36欧也在那个范围内，我就想大不了被骗一次也没啥，反正宝马嘛。高速上的车流也比我想象得多，和司机有一搭没一搭地讲着话，构建着我对赫尔辛基的第一印象。下了车，发现公寓的办公室正常2点就关门了，幸亏提前告知了我到达的时间，有工作人员在专门等我——即便如此，在寒风中提着3个箱子挣扎了10分钟也是够受的了。

从纽约到法兰克福同行的中国人有一家三口，从法兰克福到赫尔辛基有两位似乎是转机回国的中国学生和另一位似乎是入欧洲籍的女生，其他均未看到亚洲面孔。在自我隔离期间，估计更是见不到了。但正如上次在斯德哥尔摩的机场一样，中文广告到处都是，只不过之前是华为，这次变成了工商银行的全球换汇。直觉告诉我，这意味着中国和北欧三国之间存在着潜在的合作市场。这个对大多数国人而言都稍显陌生的国家，借由诺基亚、幸福指数、教育、平权和Linux被慢慢认识的地方，可能有着我们需要认真学习的技术和思想。

## 尾声

兜兜转转，在这个特殊的时间节点来到欧洲，也算是圆了一个长久以来的梦想。我们总希望把所有事情都提前规划好，然而生活，本就是不确定的，正如量子力学展现在我们面前的现实一样。人生需要规划，也需要调整。一杯敬故乡，一杯敬远方：眼里有光，心里有方向。
