---
title: 科罗拉多杂记
subtitle: 又是一年MOP
author: "Hongyang Zhou"
date: "2018-06-20"
categories: [travel]
---

用一周，了解一座城。

因为开会的缘由，第一次来到Colorado, Boulder。Denver号称one mile city，因为她恰好在海拔一英里的地方；Boulder在Denver的西北面，离落基山脉更近，海拔也再稍高一些。早上四点半就起床赶早班飞机，飞行三个小时到Denver，当地时间恰好八点。一路顺利地在学校学生宿舍入住，也不过十点前后，但要按美东时间算其实已经正午。脚还没抻利索就被同学约着去吃brunch然后hiking，为了这顿饭，还没登山呢，就走了一个小时有余。一两点钟，顶着今夏Boulder最毒一天的太阳，我们走上了市中心附近的Sanita峰的登山道。这里有一种被裹挟的感觉，若是一个人，绝不会选择在又累又困的时间爬几个小时山路的；但是有一群师弟同学围着，似乎又觉得这劳累算不上什么。我们走走停停，缓步前进，终于在一个半小时登上了最高点。这里能俯视Boulder全市的风景，远远地还能看到我落脚的学生公寓。想着自己几个小时前还在那么远的地方，这么一步一步走到山上，着实是不容易。下山的时候背包里的水也喝完了，受着阳光的炙烤，隐隐感到有些幻觉。最后靠着意志力强撑上师弟的车，冲进麦当劳对着无限续杯的饮料干了三杯醒了醒神。那时已是五点，从我起床算起一经十四个小时了。找了家中餐馆吃了晚饭，回到住处买好洗漱用品，这会都没开始呢就晒得黝黑折腾了一天，也真是年轻时候放浪形骸的生活。

Abby她们一起去了MOP的招待会，我爬完山下来一身臭汗困饿交加只好婉拒她们通行的邀请。社交是重要的一环，可我总是听不起劲头。人性生来如此，也不必勉强。

Boulder的城市规模和Ann Arbor很接近，但是风格却大相径庭。它们的房子比安娜堡还要矮，学校主体以西边的红砖房为底，却看上去比密歇根的砖来得更鲜亮活泼。城市四处是自行车道，一看便知是座自在骑行的城市。高海拔使得山上为数不多的乔木以针叶树为主，在其余灌木的覆盖之外便是裸露在外的岩石。在密歇根，你根本见不到这样的风景。

认识了位研究木星内磁层的日本女生,聊天中得知也是第二次参加MOP，着实惊艳到了我。真的好漂亮，我果然还是更加欣赏东方女性的美。

连着两天的世界杯半决赛，恰逢开会的午间休息，于是大家就一起在报告厅里看球。贾老师果然真球迷，利索地掏出笔记本，连上VPN，连上网络直播的动作麻利干净。在座的不少英法比利时同胞，不知道有没有克罗地亚的同行。克罗地亚今天加时逆转，结束哨响时，会场里也响起了阵阵掌声，对双方的表现表示敬意。

从傍晚开始，精彩的生活才要上演。沿着傍溪的路逆流而上，见着人们三五成群地在水花间嬉戏；自行车和跑者络绎不绝，小路两旁的高大树木遮出了斑驳的阴影。路的尽头接上了Boulder的市中心，到处都是下午到晚上畅饮的醒目标识。主街名为珍珠巷，酒吧餐厅书店冷饮、饰品玩具帽子服饰一应俱全。据说市中心源于当年火车通行的地方，哪里有站，哪里才有商业。如今车站早已不见，但一份精致的繁华却保留了下来。我奔着一家叫邹妈妈的小食店而来，品尝完后还是略有些失望：虽然一碗炸酱面还不错，但店内夕晒太热，东南亚裔的店员叫不出我的名字，冰绿茶并不好喝，都让我的评价打了折扣。用晚餐沿着珍珠巷自西向东而行，乡村的吉他、儿童的街舞、老人身着民族服饰脚挂铃铛的木棍舞、还有不明所以举止诡异的欢乐青年，一出一出的，彰显着小城的生机。

我在一家书店里驻足了许久，一个爸爸带着他的三个女儿也在里面选购书目。孩子们还在看书，真是对当下最大的安慰。我在地下的书柜上翻到了基本编程的数目，既有传统的Win10手册一类，也有面向青少年的java忍者游戏。据说00后都会编程，不知道是否真的如此。粗略翻了一本Stephen Wolfram写的Wolfram语言介绍，大都是一行的例子，应用范围之广完全出乎我的意料。想起跟陈楚争论未来是Matlab还是Mathematica的天下，看来唯有知己知彼，才能有所取舍——站队和信仰，时常是盲目的。

临近夜色降临，褪去了白天的炎热，鲜艳的红砖在绿色植被的包裹下也显得温暖而可爱。路过物理系的门口，看到一块石板上刻着五位诺奖得主的名字，且都是近二十年的事情。这是一所有朝气的大学。

周五的时候赶上了一个叫Red Rock的乐队在学校橄榄球场Bolsom Field举办演唱会，平时不知道躲在哪里的人们一下子都冒了出来，两天前路过时还是空空荡荡的街道一下子变得沸腾异常。在场馆外还有卖各种杂物的小摊儿，一时都让人捉摸不透到底是什么活动。提供给普通学生的运动馆径直走五分钟就到了，可由于活动封路，绕道竟花了二十分钟。

忽的想起Vasylunnas会在晚上举办音乐会，演奏管风琴（organist）。他讲英语我几乎听不懂，年纪大了走起路来也是小踱慢步，可就是实实在在的科学巨擘。我猜他也是崇拜爱因斯坦的吧，把一门古典乐器也练到和专业水平相差无几。

运动馆每逢周五做活动，所有项目全免费。他们这里的设施非常齐全，甚至比密歇根的都要好一些。从二楼篮球场的落地窗向北望去，一片苍茫的绿色，所有的房子都隐藏在树丛和高山之间，你甚至都以为所在之处便是城市的尽头。七八点钟夕阳斜照，这一框囊括了余晖下的高原美景。

最后的一天最是闲散。周六虽然仍是七点不到就被朝阳唤醒，但终得以慵懒到九点起床。我又一头扎入了校园，走访了自然历史博物馆和图书馆。这个博物馆，算是同类型里在美国逛的第三了吧，也是最小的一个。一层讲考古发现，一层讲动植物细菌，再一层……就没了。但是，我看出来了每个部分都做得很细心，没有一个坏掉的仪器，着实是难能可贵。出来后紧接走访了图书馆，发现了些很有意思的东西。期间路过了教育学院，看到了他们建院院长的留言：If you still aim for a better world, the best should teach。接着是图书馆西门正上方的告诫：One who only know his own generation remains still a child。正逢暑假的周末中午，图书馆里很空，却不乏像我一般的游客。我随意走着，就扫过了一排中文书架，书目名录着实令我震惊：《资治通鉴》、《明史》、《山海经注》、《四库全书》……他们号称是这附近最大的图书馆，我真的好奇这附近究竟有多大。我突然有兴趣会安娜堡翻翻自家学校图书馆的中文藏品。

我前前后后在校园里走了三回，已然可以不用地图穿梭自如。纵观我走过的大小校园，Boulder可以实实在在地与任一所争锋。于无声处听惊雷。

这边的空间方向有两位中国教授，其中一位楚xinzhao老师，在学生口中也快成了段子手的存在。她做的是电离层，传说中自诩精通六大领域，电离层却不在列；手下原来科大学生众多，一训起学生来就是“90后，独生子女，南方人”的标签；时不时要来个学生发顿火，不止一次被好事的大师兄健哥提前准备好录了下来。前一阵出去开会给清雨的老板捧场，结果问出的问题是“你们做这个研究有什么物理意义”……她跟手下学生强调，白天加班，晚上做实验（她们做激光雷达的，常常需要半夜），讨论问题要定量化。昊楠的老板鲁贤算是她的嫡系师弟吧，有个几岁的女儿，调皮捣蛋好动。传说Xinzhao 一次见到这个女娃，给她做了一个实验：看她坐在椅子上能维持几秒不会动。后来结论出来了，7秒。一日她跑到学生的办公室闲聊，说起这个女娃：“她啊，有点神经质，坐不住，最多维持7秒静止……你们看看这照片，是不是跟我还有点像？”那个学生一愣，思忖着是说长得像呢还是神经质的像，忽然醒悟了，连说“像，像，太像了～”这个学生没多久转了方向，去做材料了，走之前跟Xinzhao一阵促膝长谈。彼时Xinzhao心气甚高，怼天怼地，自认诺贝尔奖不在话下，听闻学生要走，不由心头一紧。她从人类的起源讲起，不知怎的就扯到了电离层关乎人类的未来。她苦于身上六大技艺后继无人，若是自己哪天驾鹤西去了便成了人类的损失。这学生一听自己换个领域和老板都扯上全人类的损失了，眼前一黑，赶紧找了个办法结束了谈话。哦对了，据说她当时还念叨着，“你说我这好好的，怎么就得了高血压呢......”

加上当年出新非线性的脑子和钓鱼、气功、女儿三大神器，这锅，估计得扣在北大的头上。

最后聊聊饮食。我实在是不敢恭维美国高校的食堂，此处的学生食堂更是把“美食荒漠”发挥到了新的高度。幸好我只是碎碎念，幸好我只用呆一周。期间尝试了三家中餐，也真是各有奇葩：第一家Five Spice台湾老板娘，菜还凑合，但更惊人的她的自信。我们讨论着点哪个豆腐，我问她有没有推荐的或者拿手的，她上来一句“哪个都擅长，哪个都好吃”。我应一句“这么自信”，她马上接着“没有底气这么会来开店”。最终我们一个豆腐菜也没点。那个三杯鸡已让我瞧出了所谓水平，我们也没饿到非要多加个豆腐不可。诚然，她不懂美食。第二家光顾的，是步行街上的小面馆。东西还是地道的，可面朝着猛烈夕晒无动于衷，而且叫不出我的名字的店员，也是美中不足之处。最后这家，中文叫“有名面馆”，在主校园的西边。在这门可罗雀的店面里，我品尝了最没人道的越南米粉，和最冷漠的服务。她明明听着我说话，却要我写字；她明知道我误解了点单的意思，却什么都不说；她看着我5选2的配菜之要了2个，分量却和5个中的2个别无二致；我想着算了吃完吧，刚放下碗筷，一只苍蝇就自觉地降落在筷子上——我毫不犹豫地在谷歌地图给了它们家最低的评分。并非所有的劳动都应得到尊重：有些人，不过是行尸走肉般地活着。

或许我不该苛责，但世界看在眼里。

