project:
  type: website

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/henry2004y
format:
  html:
    theme: spacelab
    css: styles.css



