---
format: 
  pdf: 
    documentclass: article
    geometry:
      - top=10mm
      - left=15mm
      - right=15mm
      - bottom=5mm
      - heightrounded
    fontfamily: libertine
    colorlinks: true
    fontsize: '16'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \usepackage{libertine}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}% 50% of original values
        \setlength{\columnsep}{3em}
---
<!-- TITLE -->
\begin{huge}\begin{center}{\bf Hongyang Zhou}\end{center}\end{huge}

<!-- CONTACT INFO -->
\begin{center}hongyang@bu.edu ∙ \href{https://orcid.org/0000-0003-4571-4501}{ORCID} ∙ \href{https://github.com/henry2004y}{Github}
\end{center}
\vspace{15pt}

<!-- EMPLOYMENT : 1ST BULLET-->
\begin{large}{\bf EMPLOYMENT}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf Boston University}\end{flushleft}
    \begin{flushright}Boston, MA\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}Research Scientist\end{flushleft}
    \begin{flushright}2023/10-now\end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}

\vspace{7pt}

\vspace{0.05cm}

<!-- EMPLOYMENT: 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf University of Helsinki}\end{flushleft}
    \begin{flushright}Helsinki, Finland\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}Postdoctoral Researcher\end{flushleft}
    \begin{flushright}2020/11-2023/05\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}

\vspace{7pt}

\vspace{0.05cm}

<!-- EMPLOYMENT: 3RD BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf University of Michigan}\end{flushleft}
    \begin{flushright}Ann Arbor, MI\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}Research Assistant\end{flushleft}
    \begin{flushright}2015/08-2020/09\end{flushright}
  \end{multicols}
\end{large}
\vspace{1.5pt}

<!-- EDUCATION: 1ST BULLET -->
\begin{large}
  {\bf EDUCATION}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf University of Michigan}\end{flushleft}
    \begin{flushright}Ann Arbor, MI\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
  \begin{flushleft}Ph.D of Climate and Space Sciences and Scientific Computing\end{flushleft}
  \begin{flushright}2015/08-2020/09\end{flushright}
  \end{multicols}
\end{large}

\vspace{0.05cm}

<!-- EDUCATION: 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf University of Science and Technology of China (USTC)}\end{flushleft}
    \begin{flushright}Anhui, China\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}Bachelor of Geophysics\end{flushleft}
    \begin{flushright}2011/09-2015/06\end{flushright}
  \end{multicols}
\end{large}
\vspace{1.5pt}

<!-- AWARDS : 1ST BULLET-->
\begin{large}{\bf AWARDS}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf University of Michigan}\end{flushleft}
    \begin{flushright}2020\end{flushright}
  \end{multicols}
  \vspace{-0.3cm}
  \begin{flushleft}Climate and Space Sciences Outstanding Doctoral Student Research Award\end{flushleft}
  
  \begin{multicols}{2}
    \begin{flushleft}{\bf University of Michigan}\end{flushleft}
    \begin{flushright}2016\end{flushright}
  \end{multicols}
  \vspace{-0.3cm}
  \begin{flushleft}Michigan Institute for Computational Discovery and Engineering Fellowship\end{flushleft}

  \begin{multicols}{2}
    \begin{flushleft}{\bf USTC}\end{flushleft}
    \begin{flushright}2015\end{flushright}
  \end{multicols}
  \vspace{-0.3cm}
  \begin{flushleft}Outstanding Teaching Scholarship\end{flushleft}

  \begin{multicols}{2}
    \begin{flushleft}{\bf USTC}\end{flushleft}
    \begin{flushright}2014\end{flushright}
  \end{multicols}
  \vspace{-0.3cm}
  \begin{flushleft}The First Prize, Outstanding Student Scholarship\end{flushleft}
\end{large}
\vspace{-0.16cm}

\vspace{7pt}

<!-- EXPERIENCE : 1ST BULLET-->
\begin{large}{\bf EXPERIENCE}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf Planetary Magnetosphere Modeling}\end{flushleft}
    \begin{flushright}2023/10-now\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Supervisor: Chuanfei Dong}\end{flushleft}
  \end{multicols}
\end{large}
\vspace{-0.3cm}
* Studying Earth and planetary magnetospheres with numerical simulations
* Developing kinetic shock and foreshock models

\vspace{7pt}

<!-- EXPERIENCE : 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf Hybrid Vlasov Ultra-Low Frequency (ULF) Wave Simulations}\end{flushleft}
    \begin{flushright}2020/11-2023/05\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Supervisor: Lucile Turc \& Minna Palmroth}\end{flushleft}
  \end{multicols}
\end{large}
\vspace{-0.3cm}
* Developed time-varying boundary conditions in \href{https://www.helsinki.fi/en/researchgroups/vlasiator}{Vlasiator} and the postprocessing package \href{https://henry2004y.github.io/Vlasiator.jl/stable/}{Vlasiator.jl}
* Studied ULF waves properties in Earth's magnetosheath and foreshock using global 2D simulations
\vspace{7pt}

<!-- EXPERIENCE : 3RD BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://github.com/SWMFsoftware/SWMF}{SWMF} Model Development}\end{flushleft}
    \begin{flushright}2015-2020\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Supervisor: G\'{a}bor T\'{o}th}\end{flushleft}
  \end{multicols}
\end{large}
* Developed new boundary setups and extended MPI-OpenMP parallel code capability for \href{https://github.com/SWMFsoftware/BATSRUS}{BATS-R-US}
* Developed an open-source package \href{https://henry2004y.github.io/Batsrus.jl/dev/}{Batsrus.jl} for efficient data processing, analysis and visualization
* Initiated a GPU-portable magnetohydrodynamic (MHD) solver with OpenACC, OpenMP \& CUDA

\vspace{7pt}

<!-- EXPERIENCE : 4TH BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf MHD-EPIC Simulation of Ganymede's Magnetosphere}\end{flushleft}
    \begin{flushright}2016-2020\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Supervisor: G\'{a}bor T\'{o}th \& Xianzhe Jia}\end{flushleft}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Constructed a global magnetosphere model by coupling Hall MHD with Particle-In-Cell in generalized coordinates
* Analyzed the magnetic reconnection processes at Ganymede

\vspace{7pt}

<!-- TEACHING : 1ST BULLET-->
\begin{large}{\bf TEACHING}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf Space Applications of Plasma Physics}\end{flushleft}
    \begin{flushright}University of Helsinki\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Guest Lecturer}\end{flushleft}
    \begin{flushright}2022\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.3cm}

\vspace{7pt}

<!-- TEACHING : 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf Plasma Physics}\end{flushleft}
    \begin{flushright}University of Helsinki\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Guest Lecturer}\end{flushleft}
    \begin{flushright}2022\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.3cm}

\vspace{7pt}

<!-- TEACHING : 3RD BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf Electrodynamics}\end{flushleft}
    \begin{flushright}USTC\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Teaching Assistant}\end{flushleft}
    \begin{flushright}2015\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.3cm}

\vspace{7pt}

<!-- SKILLS -->
\begin{large}{\bf SKILLS}
  \vspace{3pt}
  \hrule
\end{large}
\vspace{-0.16cm}
**Programming Languages** - Julia, Fortran, C, C++, MATLAB, Python, IDL, CUDA, Rust, Perl, LaTeX

**3D Visualization & Rendering** - Paraview, VisIt, Tecplot 

**Languages** - English, Mandarin

<!-- PUBLICATIONS : 1ST BULLET -->
\begin{large}
{\bf PUBLICATIONS}
  \vspace{3pt}
  \hrule
  \begin{flushleft}Pitch-Angle-Dependent Cosmic-Ray Transport in Anisotropic Magnetohydrodynamic Turbulence\end{flushleft}
  \vspace{-0.2cm}
  \textit{{\bf Zhou, Hongyang} and Dong, Chuanfei and Xu, Siyao},   The Astrophysical Journal, 2026
  \vspace{3pt}
  \hrule
  \begin{flushleft}Cross-Scale Coupling in Earth's Dayside Magnetosphere 2D Semi-Implicit PIC Simulation: From Global Geometry to Multi-Scale Kinetic Dynamics\end{flushleft}
  \vspace{-0.2cm}
  \textit{{\bf Zhou, Hongyang} and Dong, Chuanfei and Chen, Yuxi and Zhang, Chi and Walsh, Brian M. and Zou, Ying and Li, Xinmin},   Journal of Geophysical Research: Space Physics, 2026
  \begin{flushleft}Planar Collisionless Shock Simulations with the Semi-implicit Particle-in-cell Model FLEKS\end{flushleft}
  \vspace{-0.2cm}
  \textit{{\bf Zhou, Hongyang} and Chen, Yuxi and Dong, Chuanfei and Wang, Liang and Zou, Ying and Walsh, Brian M. and T{\'o}th, G{\'a}bor},   The Astrophysical Journal Supplement Series, 2026
  \begin{flushleft}Properties and Radial Evolution of Solar Wind Turbulence Near Mercury's Orbit\end{flushleft}
  \vspace{-0.2cm}
  \textit{Li, Xinmin and Dong, Chuanfei and Hadid, Lina Z. and Aizawa, Sae and Zhang, Chi and {\bf Zhou, Hongyang} and Wang, Liang and Gao, Jiawei and Slavin, James A.},   The Astrophysical Journal Letters, 2026
  \begin{flushleft}Direct Observations of Magnetic Reconnection in the Solar Wind Current Sheets near Mars\end{flushleft}
  \vspace{-0.2cm}
  \textit{Zhang, Chi and Dong, Chuanfei and Li, Xinmin and Shen, Han-Wen and Halekas, Jasper and Phan, Tai and Mazelle, Christian and Harada, Yuki and {\bf Zhou, Hongyang} and Gao, Jiawei},   The Astrophysical Journal Letters, 2026
  \begin{flushleft}Physics-Informed Neural Networks for Modeling the Martian Induced Magnetosphere\end{flushleft}
  \vspace{-0.2cm}
  \textit{Gao, Jiawei and Dong, Chuanfei and Zhang, Chi and Qin, Yilan and Shekarpaz, Simin and Li, Xinmin and Wang, Liang and {\bf Zhou, Hongyang} and Tadlock, Abigail},   Geophysical Research Letters, 2026
  \begin{flushleft}Global Mapping of Magnetic Field Topologies in the Martian Induced Magnetosphere\end{flushleft}
  \vspace{-0.2cm}
  \textit{Zhang, Chi and Dong, Chuanfei and Xu, Shaosui and Halekas, Jasper and Luhmann, Janet and Shen, Han-Wen and {\bf Zhou, Hongyang} and Wang, Xiao-Dong and Gao, Jiawei and Li, Xinmin and others},   Journal of Geophysical Research: Space Physics, 2026
  \begin{flushleft}Spectral Properties and Energy Injection in Mercury's Magnetotail Current Sheet\end{flushleft}
  \vspace{-0.2cm}
  \textit{Li, Xinmin and Dong, Chuanfei and Wang, Liang and Aizawa, Sae and Hadid, Lina Z. and Zhang, Chi and {\bf Zhou, Hongyang} and Slavin, James A. and Gao, Jiawei and Stumpo, Mirko and others},   Geophysical Research Letters, 2026
  \begin{flushleft}Revisiting Mars' Induced Magnetic Field and Clock Angle Departures Under Real-Time Upstream Solar Wind Conditions\end{flushleft}
  \vspace{-0.2cm}
  \textit{Cheng, Zhihao and Zhang, Chi and Dong, Chuanfei and {\bf Zhou, Hongyang} and Gao, Jiawei and Tadlock, Abigail and Li, Xinmin and Wang, Liang},   Journal of Geophysical Research: Space Physics, 2025
  \begin{flushleft}Global Energy Transport and Conversion in the Solar Wind--Mars Interaction: MAVEN Observations\end{flushleft}
  \vspace{-0.2cm}
  \textit{Zhang, Chi and Dong, Chuanfei and {\bf Zhou, Hongyang} and Halekas, Jasper and Li, Xinmin and Gao, Jiawei and Shen, Han-Wen and Wang, Xiao-Dong and Nilsson, Hans and Ramstad, Robin and others},   Journal of Geophysical Research: Planets, 2025
  \begin{flushleft}Observation of a Knotted Electron Diffusion Region in Earth's Magnetotail Reconnection\end{flushleft}
  \vspace{-0.2cm}
  \textit{Li, Xinmin and Dong, Chuanfei and Ji, Hantao and Zhang, Chi and Wang, Liang and Giles, Barbara and {\bf Zhou, Hongyang} and Chen, Rui and Qi, Yi},   Geophysical Research Letters, 2025
  \begin{flushleft}Control of Solar Wind on Magnetic Field Fluctuations in the Subsolar Magnetosheath\end{flushleft}
  \vspace{-0.2cm}
  \textit{Zou, Ying and Walsh, Brian M. and Chen, Yuxi and {\bf Zhou, Hongyang} and Raptis, Savvas},   Journal of Geophysical Research: Space Physics, 2025
  \begin{flushleft}The Early-Phase Growth of ULF Waves in the Ion Foreshock Observed in a Hybrid-Vlasov Simulation\end{flushleft}
  \vspace{-0.2cm}
  \textit{Zhang, Kun and Dorfman, Seth and Turc, Lucile and Ganse, Urs and Shi, Chen and {\bf Zhou, Hongyang} and Palmroth, Minna},   Journal of Geophysical Research: Space Physics, 2025
  \begin{flushleft}BATSRUS GPU: Faster-than-real-time Magnetospheric Simulations with a Block-adaptive Grid Code\end{flushleft}
  \vspace{-0.2cm}
  \textit{An, Yifu and Chen, Yuxi and {\bf Zhou, Hongyang} and Gaenko, A. and T{\'o}th, G{\'a}bor},   The Astrophysical Journal, 2025
  \begin{flushleft}Interplay Between a Foreshock Bubble and a Hot Flow Anomaly Forming Along the Same Rotational Discontinuity\end{flushleft}
  \vspace{-0.2cm}
  \textit{Turc, L. and Archer, M. O. and {\bf Zhou, Hongyang} and Pfau-Kempf, Y. and Suni, J. and Kajdi\v{c}, P. and Blanco-Cano, X. and Dahani, S. and Battarbee, M. and Raptis, S. and others},   Geophysical Research Letters, 2025
  \begin{flushleft}Ion-Mediated Tearing and Kink Instabilities in the Earth's Magnetosphere: Hybrid-Vlasov Simulations\end{flushleft}
  \vspace{-0.2cm}
  \textit{Zaitsev, I. and Cozzani, G. and Alho, M. and Horaites, K. and {\bf Zhou, Hongyang} and Kit, A. and Pfau-Kempf, Y. and Hoilijoki, S. and Ganse, U. and Battarbee, M. and others},   Journal of Geophysical Research: Space Physics, 2025
  \begin{flushleft}Role of ULF Waves in Reforming the Martian Bow Shock\end{flushleft}
  \vspace{-0.2cm}
  \textit{Zhang, Chi and Dong, Chuanfei and Liu, Terry Z. and Mazelle, Christian and Raptis, Savvas and {\bf Zhou, Hongyang} and Fruchtman, Jacob and Halekas, Jasper and Li, Jing-Huan and Hanley, Kathleen G. and others},   AGU Advances, 2025
  \begin{flushleft}Anomalous Transient Enhancement of Planetary Ion Escape at Mars\end{flushleft}
  \vspace{-0.2cm}
  \textit{Zhang, Chi and Dong, Chuanfei and {\bf Zhou, Hongyang} and Halekas, Jasper and Yamauchi, Masatoshi and Nilsson, Hans and Liu, Terry and Persson, Moa and Curry, Shannon and Dong, Yaxue and Futaana, Yoshifumi and Chen, Yuxi and Zhou, Muni and Suranga, Ruhunusiri and Hanley, Kathleen and Mazelle, Christian and Xu, Shaosui and Ramstad, Robin and Holmstrom, Mats and Chen, Li-Jen},   Nature Communications, 2025
  \begin{flushleft}Observational characteristics of electron distributions in the Martian induced magnetotail\end{flushleft}
  \vspace{-0.2cm}
  \textit{Zhang, Chi and Dong, Chuanfei and {\bf Zhou, Hongyang} and Deca, Jan and Xu, Shaosui and Harada, Yuki and Curry, Shannon M and Mitchell, David L and Liu, Zhi-Yang and Qin, Junfeng and others},   Geophysical Research Letters, 2025
  \begin{flushleft}Interplay of magnetic reconnection and current sheet kink instability in the Earth's magnetotail\end{flushleft}
  \vspace{-0.2cm}
  \textit{Cozzani, Giulia and Alho, M and Zaitsev, Ivan and {\bf Zhou, Hongyang} and Hoilijoki, Sanni and Turc, Lucile and Grandin, Maxime and Horaites, Konstantinos and Battarbee, Markus and Pfau-Kempf, Yann and others},   Geophysical Research Letters, 2025
  \begin{flushleft}The Vlasiator 5.2 Ionosphere--Coupling a magnetospheric hybrid-Vlasov simulation with a height-integrated ionosphere model\end{flushleft}
  \vspace{-0.2cm}
  \textit{Ganse, Urs and Pfau-Kempf, Yann and Zhou, Hongyang and Juusola, Liisa and Workayehu, Abiyot and Kebede, Fasil and Papadakis, Konstantinos and Grandin, Maxime and Alho, Markku and Battarbee, Markus and others},   Geoscientific Model Development Discussions, 2024
  \begin{flushleft}Hybrid-Vlasov modelling of ion velocity distribution functions associated with the Kelvin-Helmholtz instability with a density and temperature asymmetry\end{flushleft}
  \vspace{-0.2cm}
  \textit{Tarvus, Vertti and Lurc, Lucile and {\bf Zhou, Hongyang} and Nakamura, Takuma and Settino, Adriana and Blasl, Kevin and Cozzani, Giulia and others},   AAS, 2024
  \begin{flushleft}Source of Drift-dispersed Electrons in Martian Crustal Magnetic Fields\end{flushleft}
  \vspace{-0.2cm}
  \textit{Zhang, Chi and {\bf Zhou, Hongyang} and Dong, Chuanfei and Harada, Yuki and Yamauchi, Masatoshi and Xu, Shaosui and Nilson, Hans and Ebihara, Yusuke and Curry, Shannon M. and Qin, Junfeng and Mitchell, David L. and Brain, David A.},   Astrophysical Journal, 2024
  \begin{flushleft}Finding reconnection lines and flux rope axes via local coordinates in global ion-kinetic magnetospheric simulations\end{flushleft}
  \vspace{-0.2cm}
  \textit{Alho, M., Cozzani, G., Zaitsev, I., Kebede, F. T., Ganse, U., Battarbee, M., Bussov, M., Dubart, M., Hoilijoki, S., Kotipalo, L., Papadakis, K., Pfau-Kempf, Y., Suni, J., Tarvus, V., Workayehu, A., {\bf Zhou, H.}, and Palmroth, M.},   Annales Geophysicae, 2024
  \begin{flushleft}Kinetic signatures, dawn-dusk asymmetries, and flux transfer events associated with Mercury's dayside magnetopause reconnection from 3D MHD-AEPIC simulations\end{flushleft}
  \vspace{-0.2cm}
  \textit{Li, Changkun and Jia, Xianzhe and Chen, Yuxi and T{\'o}th, G{\'a}bor and {\bf Zhou, Hongyang} and Slavin, James A and Sun, Weijie and Poh, Gangkai},   JGR, 2024
  \begin{flushleft}Dayside Pc2 Waves Associated With Flux Transfer Events in a 3D Hybrid-Vlasov Simulation\end{flushleft}
  \vspace{-0.2cm}
  \textit{Tesema, Facil and Palmroth, Minna and Turc, Lucile and {\bf Zhou, Hongyang} and Cozzani, Giulia and Alho, Markku and Pfau-Kempf, Yann and Horaites, Konstantinos and Zaitsev, Ivan and Grandin, Maxime},   GRL, 2024
  \begin{flushleft}Vlasiator. jl: A Julia package for processing Vlasiator data\end{flushleft}
  \vspace{-0.2cm}
  \textit{{\bf Zhou, Hongyang}}, Journal of Open Source Software, 2023
  \begin{flushleft}FLEKS: A flexible particle-in-cell code for multi-scale plasma simulations\end{flushleft}
  \vspace{-0.2cm}
  \textit{Chen, Yuxi and T{\'o}th, G{\'a}bor and {\bf Zhou, Hongyang} and Wang, Xiantong}, CPC, 2023
  \begin{flushleft}Enabling technology for global 3D + 3V hybrid-Vlasov simulations of near-Earth space\end{flushleft}
  \vspace{-0.2cm}
  \textit{Ganse, U. and Koskela, T. and Battarbee, M. and Pfau-Kempf, Y. and Papadakis, K. and Alho, M. and Bussov, M. and Cozzani, G. and Dubart, M. and George, H. and Gordeev, E. and Grandin, M. and Horaites, K. and Suni, J. and Tarvus, V. and Kebede, F. T. and Turc, L. and {\bf Zhou, H.} and Palmroth, M.}, Physics of Plasmas, 2023
  \begin{flushleft}Magnetospheric Response to a Pressure Pulse in a Three-Dimensional Hybrid-Vlasov Simulation\end{flushleft}
  \vspace{-0.2cm}
  \textit{Horaites, Konstantinos and Rintam{\"a}ki, E and Zaitsev, I and Turc, L and Grandin, M and Cozzani, G and {\bf Zhou, Hongyang} and Alho, M and Suni, J and Kebede, F and others}, JGR, 2023
  \begin{flushleft}Magnetotail plasma eruptions driven by magnetic reconnection and kinetic instabilities\end{flushleft}
  \vspace{-0.2cm}
  \textit{Palmroth, Minna and Pulkkinen, Tuija I and Ganse, Urs and Pfau-Kempf, Yann and Koskela, Tuomas and Zaitsev, Ivan and Alho, Markku and Cozzani, Giulia and Turc, Lucile, {\bf Zhou, Hongyang} and others}, Nature Geoscience, 2023
  \begin{flushleft}First 3D hybrid-Vlasov global simulation of auroral proton precipitation and comparison with satellite observations\end{flushleft}
  \vspace{-0.2cm}
  \textit{Grandin, M. and Luttikhuis, T. and Battarbee, M. and Cozzani, G. and {\bf Zhou, H.} and Turc, L. and Pfau-Kempf, Y.},   Journal of Space Weather and Space Climate, 2023
  \begin{flushleft}Magnetospheric responses to solar wind Pc5 density fluctuations: Results from 2D hybrid Vlasov simulation\end{flushleft}
  \vspace{-0.2cm}
  \textit{{\bf Zhou, Hongyang} and Turc, Lucile and Pfau-Kempf, Yann and Battarbee, Markus and Tarvus, Vertti and Dubart, Maxime and George, Harriet and Cozzani, Giulia and Grandin, Maxime and Ganse, Urs}, Frontiers in Astronomy and Space Sciences, 2022
  \begin{flushleft}A global view of Pc3 wave activity in near-Earth space: Results from hybrid-Vlasov simulations\end{flushleft}
  \vspace{-0.2cm}
  \textit{Turc, Lucile and {\bf Zhou, Hongyang} and Tarvus, Vertti and Ala-Lahti, Matti and Battarbee, Markus and Pfau-Kempf, Yann and Johlander, Andreas and Ganse, Urs and Dubart, Maxime and George, Harriet and others}, Frontiers in Astronomy and Space Sciences, 2022
  \begin{flushleft}Quasi-parallel Shock Reformation Seen by Magnetospheric Multiscale and Ion-kinetic Simulations\end{flushleft}
  \vspace{-0.2cm}
  \textit{A. Johlander and M. Battarbee and L. Turc and U. Ganse and Y. Pfau-Kempf and M. Grandin and J. Suni and V. Tarvus and M. Bussov and {\bf H. Zhou} and others}, GRL, 2022
  \begin{flushleft}Estimating inner magnetospheric radial diffusion using a hybrid-Vlasov simulation\end{flushleft}
  \vspace{-0.2cm}
  \textit{H. George and E. Kilpua and A. Osmane and S. Lejosne and L. Turc and M. Grandin and M. M. H. Kalliokoski and S. Hoilijoki and U. Ganse and M. Alho and M. Battarbee and M. Bussov and M. Dubart and A. Johlander and T. Manglayev and K. Papadakis and Y. Pfau-Kempf and J. Suni and {\bf H. Zhou} and M. Palmroth}, Frontiers in Astronomy and Space Sciences, 2022
  \begin{flushleft}Reconnection-driven dynamics at Ganymede's upstream magnetosphere: 3-D global Hall MHD and MHD-EPIC simulations\end{flushleft}
  \vspace{-0.2cm}
  \textit{{\bf Zhou, Hongyang} and T{\'o}th, G{\'a}bor and Jia, Xianzhe and Chen, Yuxi}, JGR, 2020
  \begin{flushleft}Efficient OpenMP parallelization to a complex MPI parallel magnetohydrodynamics code\end{flushleft}
  \vspace{-0.2cm}
  \textit{{\bf Zhou, Hongyang} and T{\'o}th, G{\'a}bor}, Journal of Parallel and Distributed Computing, 2020
  \begin{flushleft}Embedded kinetic simulation of Ganymede's magnetosphere: Improvements and inferences\end{flushleft}
  \vspace{-0.2cm}
  \textit{{\bf Zhou, Hongyang} and T{\'o}th, G{\'a}bor and Jia, Xianzhe and Chen, Yuxi and Markidis, Stefano}, JGR, 2019
\end{large}