---
title: 圣地亚哥杂记
subtitle: 圣诞旅行
author: "Hongyang Zhou"
date: "2026-01-06"
categories: [travel]
---

今年圣诞和宝、獾一起飞到了加州圣地亚哥，自驾旅行了一周。第三次到加州，首次来到圣地亚哥，又是一番新奇的体验。一边旅行一边画图改稿子，现代的工作早已脱离的物理的局限，更多的精神层面的投入和平衡。

这次从波士顿往返圣地亚哥，刚好从东北到西南跨越了整个美国大陆。出发时正值圣诞，清晨7点的飞机，我们提前订好了Uber的黑车，四点多爬起来赶去机场。之前在密歇根的时候被坑过一回，普通的Uber叫车服务即便提前预订，也是在指定时间的一小时前放单，于是小地方的凌晨根本没人接单。一个月前在波士顿搭车遇到一位中国司机，跟他咨询后才得知只有Black Ride提供确认预订，于是这次便选择试用一下。圣诞的凌晨，摸黑乘车奔驰到了机场，C航站楼一如既往的繁忙，拖家带口的人们和我们一样赶着出去旅行。提前准备的麦当劳汉堡出门前没来得及加热透，内部仍是凉的，不免得被数落了一通。赶在最后关头总有忙不过来的情况，引以为戒。

圣地亚哥机场离城市非常近，降落的时候正好掠过中心区。我们提前租好了车，除了出停车场查验驾驶证，全程无人服务。这辆SUV也是个历经七万迈的老江湖了，踩油门明显有种壮志未酬的感觉，但依旧时不时吼两嗓子。宝提前查好了吃饭了地方，我们饿了两顿，直奔北边的小面馆。一碗豌杂、一碗牛肉面、一份狼牙土豆，吃得精光。吃完驾车来到圣地亚哥市里面的大公园徒步，弄了半天没明白停车费该如何支付，问了旁边车上一大姐得知直到年底都免费，笑着让我们享受最后的免费时光。沿着绿地走，路过一座高架桥，墨西哥风情的建筑扑面而来，博物馆都没开，但沿路的游人依旧络绎不绝。

隔天，中途岛号航母参观，是我继明斯克航母之后第二艘参观的航母，也是继去年夏威夷参观二战驱逐舰后又一次登上军舰。小时候去明斯克的记忆已然不深了，但很显然中途岛号大了一截，内部能容纳4500人作业，1945年下海，1992年才由于火灾正式退役。

UCSD开车绕了一圈，自成一体的校园，铺陈的建筑和校园风貌令我眼前一亮，仿佛来到了中国南方的校园。隶属于UCSD的水族馆40刀一人的门票破天荒的贵，里面东西不多，但是工作人员非常友善，露台直面太平洋，一半的门票价都献给了大海。

洛杉矶的酒店列了十个可以访问的景点，我们误打误撞走过来五个：Rodeo Drive，贝弗利山下的购物街，高端商店里品尝了20刀一杯的奶昔；Santa Monica Pier，晚上开车兜风走马观花看了一眼；格里菲斯天文台，周一闭馆，但晚上九点依旧游人如织，我们准备付停车费时还得到好心黑人老哥赠送的停车票；星光大道，沿路都是美国演艺圈的著名演员留名的地砖，但两旁略有衰落萧条之感；环球影城，出乎意料地人多，每个项目基本上都排队个把小时，遗憾错过了影片拍摄地参观火车游，但久违地让我又乘坐了几把过山车。

租车一共开了800迈约1300公里，除了到洛杉矶那天的快速路上有些惊险，以及在约书亚树公园等待入园走走停停的疲乏，其余时候的驾驶体验还是很好的。

圣地亚哥和洛杉矶市里面的流浪汉依旧不少。圣诞期间，圣地亚哥市中心只有车流没有人流，高楼群下面四处可见推车、麻袋和帐篷。初到洛杉矶那天下午，我定错了导航的酒店位置，抵达时宝说周围都是流浪汉，住这儿都不敢下楼走，才意识到是弄错了地址。比弗利山附近就好很多，我们的酒店附近不少高层公寓，很类似国内的楼房，打理得干净现代。流浪汉聚集在市中心，一直是美国城市的一大特色，也是自由的代价。

未整理完，稍后再来。