---
title: 洛杉矶杂记
subtitle: ISSS
author: "Hongyang Zhou"
date: "2018-09-14"
categories: [travel]
---

# 09/06/2018

第一次来洛杉矶，来到了加州大学洛杉矶分校。这时仍是他们的夏季学期，但学校里却依然人潮涌动。来回两遍，我已经对这里的方位烂熟于心。
齐怡师妹很热情，这其实只是我第二次跟她讲话，然而人家开组会到六点多还依旧请我们出来吃东西，并一路把我们送回住处。和她聊天的过程中，有种安心的感觉——或许就是师妹的人格魅力。那种不紧不慢、娓娓道来的谈吐，和大方得体，出落有度的风范，看得出门第。四川妹子，了不得。看清一个人本不需要很久，只在于你的观察是否用心。

# 09/07/2018

夜幕下的格里菲斯天文台，迷雾中的洛杉矶夜景。在木星和土星之间驻足留影，和外号“大猩猩”的美国人讲着中文谈笑风生。偶遇林峰，也是一种缘分。

# 09/09/2018

Camilla带着我跟Yash参观了UCLA的地球物理系、物理系和天文台。惊讶地发现他们这里大部分的地方大门不锁，出入数学楼的屋顶轻而易举。殊不知，站台天台上，真的能看到璀璨的星空，即便是繁华如洛杉矶。Camilla说她以前经常来这里，特别喜欢天台的感觉。仰望星空的习惯，也许就是这样培养起来的吧。她跟我们讲了很多学校的趣闻，比如物理系门口的反向喷泉。传说在校学生如果不小心溅到了喷泉的水就会挂科，所以在毕业季，常会看到即将离校的学生把曾经的作业和考卷丢进喷泉里——因为他们再也不用担心成绩的问题了。物理系的老楼楼檐上涂画着各式神奇的图案，像极了外星人留下的讯息。

这几天快到他们开学的日子，一波又一波的新生被分成了一个个小团体开始各类熟悉校园的活动。大清早广场上人满为患人头攒动，到了晚上只听见沿路引吭高歌恣肆大笑。Camilla和Yash在感慨，现在的年轻人打成一片的时间真是快得惊人。回想当初，Camilla说最开始和她在一起分组活动的伙伴，后来几乎再也没有在学校有过交集。大学的分化和选择有多繁杂，可见一斑。

我们聊天，聊七宗罪、聊金钱的罪恶、聊饮食、聊老师。直到这一刻我才感到，思想的交流也可以通过非母语来完成。这种人生的思辨，语言不过是一种载体。语言当然是重要的；但我一直觉得，一个人对于思考、对于情绪的体察、对于条理的分析，是不存在语言的障碍的。人类这一物种神奇的其中一处，便是我们殊途同归的内核构造。

# 09/12/2018

这次会议让我受益良多。我终于感觉自己能学习到很多不了解的东西，也能认知到众多方法的来龙去脉。以人为鉴知得失，你能看清好坏，辨明真伪，就已不易。诚然，我还是不擅长交际，也不是那么喜欢交际。但是，在科学这种领域，懂的自然懂，不懂装懂就是件累人的差事。真才实学，是我一直追求的境界。

Yash有一个设计并实现电离层电磁模型的想法，用以取代现有的静电模型。我非常想和他一起做这个项目。

# 09/13/2018

申请经费要趁早：这活耗时耗力，却不一定有好结果。

晚宴上，当David展示出当年他的导师和学生们在一起的照片，我不禁感慨良多。照片里的诸位，如今几乎都是教授级别的人物，依旧活跃在科研的舞台上。这个模拟的国际学校已经办了13届了，并且依旧充满了活力。受益良多，远比于其他的会议。

# 09/14/2018

仍旧感到有些寂寥。谁不想身边有人陪伴的感觉。怅然若失，不能自拔。



