---
title: 仙台之行
subtitle: 又是一年MOP
author: "Hongyang Zhou"
date: "2019-06-22"
categories: [travel]
---

借着到日本开会的机会，我第一次真正走进了这个神奇的国度。在讯息发达和文化融合的今天，称得上陌生的东西不多，但可以思考和观赏的地方也不少。

会议是由日本东北大学承办的，坐落于东京以北300公里的仙台市。东北大学起家于当年鲁迅先生求学的仙台医学院，而我们前四天的会址就离鲁迅曾经读书的地方相距不过百米。如今的仙台已不是百年前先生读书时的小镇模样，而是更接近一座现代化的中型城市，有百万人口，两线地铁，和成熟的规划。从东京车站乘新干线不过一个半小时，观赏着沿路和中国几分相似的风景，便来到了日本北方的重镇。这里的车牌都是四位数加一个假名，起初我还惊讶于可能的汽车保有量至少；直到我后来意识到假名有50个且车牌颜色也有区别，其实也是足够了。

日本有三种文字：表音的平假名和片假名，表形的汉字，以及源起于注音的罗马字。假名据说最初是由传入的汉字取其发音简化而来，也是对国人来说最难以理解的部分之一，看得我眼花缭乱。但许多场合都会混着使用汉字，所以连蒙带猜也能估摸出许多指示牌的意思。但另一个令国人头疼的问题，是日文人名地名的汉字与罗马字的对应关系——对于不熟悉日文发音的我们，把表音的罗马字和表意的汉字对应起来又多了一层额外的负担。我曾经问过一个日本友人他们在什么时候会使用对应的文字，他只是笼统地向我描述了一下，并表示这大多只是历史习惯，其实多数时候都可以互相替换。在网上也缺少明确的答案，许多人的回答只是让我笼统地感觉到假名的地位在逐渐升高，而汉字则趋向于成为古典文学一类。有天晚上我在酒店里看电视，一个闯关的娱乐节目里一群人在组队挑战汉字的书写，可见对于全民基本教育世界领先的日本人来说写对汉字也不是件寻常轻松的事。

传闻中的日本高度发达，老龄化严重，我的直观感受却没有那么深切。倒是从羽田机场出来后问路寻求帮助都受到了极其热情的帮助，给人的第一印象极其舒服。一到东京车站，人来人往车水马龙，即便是周日，穿着西装制服的人们也是络绎不绝，让我切身体会到一丝隐藏的压力。在仙台的周五也赶了一次早高峰，摩肩接踵的地铁和疾行的人流，像极了国内的熟悉场景。不过还是很容易分辨这是日本：所有的通行跟国内都是镜像的，因为他们沿用了英式的习惯；扶手电梯里不会反复播出“靠右站稳，左侧通行”的广播，多年的教化已经在社会中形成了约定俗成的准则。

高度发达的现代社会有几个标志性的事物，而提起日本，就不得不提便利店这一现代城市的产物。即便在仙台这样大概规模排名第十的日本城市，哆啦A梦里面刚田家的杂货铺也已不复存在，取而代之的便是无处不在的便利商店。传说中的三大巨头7-11，Lawson和Family Mart，在我的视觉上反映出的可能更是7-11一家独大的态势。这些24小时营业的便利店，对成长在深圳的我来说熟悉又陌生，又切实地解决了开会期间早餐和夜宵的问题，想起来也是极其满意的。那些熟悉的面包卷、三文治和泡面的味道，可以说是这座城市的温情，亦或者解读成都市淡漠的人情。我的确没有见到早餐铺上飘来的阵阵香气，也不见任何小贩沿街的吆喝叫卖声。那都是古老的记忆，已不再属于现在的仙台。但对我来说，比之美式的“荒漠”，这里已足够欣喜。

绕不过的话题当然是吃。我满载期待而来，兴尽之余满足之情仍溢于言表。从小我便喜欢日本料理；即便到了美国，约莫每两周总有一顿仍是日料。国内的日料总体要优于美国的日料，也不存在植根于美国的本土化衍生产品酱汤和姜丝沙拉。但真到了日本，我算是见识了什么是真正的日料。如果用一个字概括，那毫无疑问，就是“鲜”。第一顿午餐，东北大学的餐厅，日式的食堂有着便宜而精致的风味。到晚上，吃到了可能是目前为止我品尝过的最浓郁的豚骨拉面。一碗不到1000yen，虽然只有两片猪肉，但是汤底、豆芽、葱绿和主料的拉面，都是顶级的口感。汤底中加上了咸蛋黄，有近一步促进浓郁的效果。据张公子转述日本拉面的汤底无外乎是昆布和鱼，加上猪骨一类；但要论对品质的把控，果然还是日本人最为重视。就譬如再次造访东北大学的食堂时，那生鲜的番茄，整颗置于一小碟中，只片四份，真是令人回味无穷。在日本蔬菜是精贵的东西，政府为了保护本国农业，大大拉高了进口蔬菜的关税，直接或间接扶持了相当部分的本国农产品。小而精，说日本农业，一点也不过誉。就凭这偶然碰到的大学食堂里的番茄，洗净生食；在很多地方，哪有这样的魄力和自信，把食物就这么简单地端到食客的面前？更不要提在松岛町品尝的牛舌定食，那真是神仙滋味。如果问我此行珍馐之最，这家海边的牛舌小店当之无愧，也不枉我步行15分钟等候半个小时。当然，有对比才有层次感：同样是牛舌，在安娜堡Seoul Garden的风味远远不及，在主办方当地闹市区的晚宴中呈上的大盘亦是远远不及。那顿晚宴唯一的亮点在于清酒烧酒梅酒的百花齐放，若是论菜品质量，估计店里的伙计也没见识过这么大的阵仗，一通手忙脚乱之下连牛舌也煎得老气横秋。

最后一晚，我们密歇根几人相聚一地下居酒屋（Isakaya），体验了把地道的日式聚餐。食物中除了大家都不甚能接受的纳豆，其余都是水准之上。那款纳豆被包裹在豆腐里炸制，味道诡异却在我看来远不如臭豆腐的香。Abby强推的毛豆制品Zunda（毛豆沙糕）也是惊喜之作，无论是与大福相伴或是与巧克力相融，都能呈现出圆润的滋味。令人颇为惊奇的是居酒屋内竟然允许吸烟，日本人的聚会场所果然还是要允许一些奔放的东西存在。

整洁、干净，这一点无论在东京、横滨还是仙台都是如一的。我没有在街上见过环卫工人，不知道他们到底是如何保持街道的整洁的；但那日在地铁站出口注意到一位拿着吸尘器一丝不苟地清理角落里的灰尘的大叔，至少印证了日本人对干净的极致追求。在松岛町的神社附近散步时，无论是山腰的墓碑还是居民住房前后的街道，那种规整和干净，是现代人类文明的杰出代表。人不是为了活着而活着，而是为了某种追求而活着。那些房屋也谈不上多精致漂亮，但是干练、素雅。而如果上升到了某些信仰上的追求，体现在瑞严寺内的装潢遍可见一斑。这是松岛町内日本国宝级的寺庙，古松参天，主体建筑全悉木制，入寺须拖鞋，踩在一块块木板上只呀作响，却似不落纤尘。那房梁上的雕花，室内屏风纸门的版画，每一小块，估计都要花费一位精湛工匠少则数十日多则半年记的时光。寺庙各处皆是活动的板门，透气通光，随处即是养心修禅的良所。还有室外石窟下的佛像和展览室里的墨宝，所有的一切汇聚在一起，与国内众多烧香求佛的沸腾之地拉开了境界上的差距。此心安处是吾乡，切切实实、肌肤之感。

很多小方面也体现出日本的特色。譬如那无处不在的雨伞架，以及众多空置的雨伞，可能是人们遗忘的，也可能是故意剩下的；众多换汇、卖票的结算场所都有老式的计算器，纵使再先进的电脑似乎用起来也不如这简单的计算器顺手。他们会把计算器面朝着顾客，然后在你面前飞速地敲击键盘——这阵仗，我是又惊又怵，其实无论她敲出什么数字估计我都认账。还有东京随处可见的乌鸦，日本国鸟级的待遇，集祥瑞与恐惧于一身，神秘莫测。最后，也是我此行最费解和不满的地方，就是现金。都已经2019年了，到处还是仅收现金，作为发达国家，真是不及格的方面。离开日本前有几个小时的时间，到达东京后本想就近到国立艺术馆或是科技馆逛一逛，可哪知堂堂国立的展览馆竟然仅收现金，让拖着行李箱绕着日本皇居走了半个小时而来的我气得直跳脚。早知如此，我还不如到车站北边不远处的东京大学走一遭呢。社会的发展总有不尽如人意的地方，而在思考中改变和提高，是世界范围内不变的主题。

于是乎，我结束了为期一周的日本行，又坐着加拿大航空的头牌航线返回了美国。那些惊艳与遗憾，都留待着日后重新发掘。我没有接着玩，其实也是有原因的。希望下次，能与你一同前来。
