---
title: 东游记
subtitle: 从安娜堡到纽约
author: "Hongyang Zhou"
date: "2018-07-30"
categories: [travel]
---

白雾飞溅成雾，阳光幻化成虹；隆隆落水相伴，偏偏海鸥共舞。

一路东行，从安娜堡出发，到克利夫兰、水牛城、大瀑布、波士顿、然后纽约。

出来旅行一趟，父亲丢了一根充电线，母亲丢了一件毛衣，还差点把自己手机丢在别人餐厅里。人年纪大了就是容易丢东西，没法回避的话，关键在于如何防范和面对这样的遭遇。丢东西不可怕，可怕的是持续的抱怨和负面情绪。共勉。

Fort Lee有家包不同，上海菜，水平之高着实令人惊异。相比之下，法拉盛的南翔小笼就相形见绌了。中国人常言酒香不怕巷子深，那天在包不同，我们足足等了40分钟，吃完出来八点多还是有人在等位，足见这店家的口碑。

自己在纽约游荡的日子，这次逛了一圈在皇后街的纽约科技馆。科技馆在1964年世博会的旧址上，其余的地方也被改造成公园、运动场，以及博物馆和动物园。每年一度的美网也在这里举行，各类运动的爱好者们也屡见不鲜。最有意思的一种可供出租的手摇式自行车，人几乎是躺在里面，全凭手臂摇动把手前进，速度也不见得慢。
科技馆没有我想象的大，里面全是孩子，布展也是略显凌乱。作为科技馆，和一般博物馆最重要的区别在于互动性——这一点上，它做得很出色：几乎所有的展览都可以动手操作，鲜有维修或是坏了的机器。小朋友们哪里有耐心阅读所有的说明文字，大都是上去一顿操作，如果没有得到及时的反馈就很快丧失兴趣，进而转向下一个展品。也就像我这种悠哉的游客还懂一些科学，看到感兴趣的展品会仔细端详一阵。偶然间看到一台出错的电脑，Suns的机器报错在黑白屏上，倒是让我驻足看了一会。一个馆里的年轻伊斯兰女孩儿看到了这一幕，过来问我是否知道怎么维修这台电脑。我笑笑说其实也不怎么懂，只是快有个计算机的辅修学位，看到这些东西可能有些兴趣。她又问我那我的主修是什么，我说是物理。她一脸惊叹和略显崇拜的表情，告诉我前面还有很多物理展览可以看看。我有些小得意，又又点不太好意思，说我就是感兴趣才来参观的。最后一句祝福，我们便分开了。单纯而可爱的姑娘。
倒还是有些收获。看到了数学家们如何嘲笑物理学家、化学家的思维逻辑；看到了几何曲线最直观的美；知道了一种证明圆柱和平面的截面是椭圆的方法；看到了Zeta函数的几何形状；看到了闵可夫斯基几何的精妙结论；看到了古老而直观的网格灯泡乘法器；看到一张近现代数学从15世纪以来由巨人谱写的年表.；看到了木卫三掠过大红斑的壮观图片.....我忽然想起了伟大科学家朴素观念的开端：时间与空间的联系；事物与周期性的联系；连续和离散的关系；数字和几何的关系......重要的是想法。
