---
title: DC 三番记
author: "Hongyang Zhou"
date: "2018-12-15"
categories: [travel]
---


第三次来华盛顿了，一开始找路的时候才发现，还是不够了解这座城市。下了地铁找个路南北都能弄反，回忆了半天愣是没想起来曾经住过的宾馆在哪里。直到重新绕着市中心转了一圈，在中国城里曾经吃过的馆子再来一遍，才让过往的记忆浮出水面，重焕光彩。最终才发现，现在住的Marriot，离曾经的Renaissance，不过一百米的距离。我见识过的财政部、国防部、白宫、华盛顿纪念碑、林肯纪念堂、美国历史博物馆、国家自然历史博物馆、奥巴马喜欢的Shake Shack 快餐店……隐藏的记忆里的老地方，需要一点点被唤醒。

# 忆往昔

上次来这里，误打误撞地找上瑞典驻美国领事馆，在华盛顿港附近徘徊了两个小时，虽然险些误了正事，但也算见识到了河岸边的绮丽风景。在出租车上赶路又恰巧看见了绝美的丛林风景，同非洲兄弟的一席聊天也道出了生活的不定和机遇。之后在国会山和中央车站间闲逛了一个下午，连着之前一家人在美国国庆逛过的地方，算是把整条中轴线补了个全。论壮观程度，美国的首府真不算什么；但这里反映出的国家精神和人民意志，却是全世界其他国家需要借鉴和学习的。

# 看而今

这次来开AGU年会，完全本着轻松愉悦的心态。虽然文章依旧没有发出来，但是我更淡定了，更从容了，更明白自己在意的是什么了。华盛顿是个我熟悉又陌生的城市，也是期待着这些天的美妙际遇：曾经的老师们还在不在，同学们过得好不好，睿智的姑娘们会不会经过我的身旁？

第二次参观空间博物馆，看得比第一次稍微细致了些。平常周日的早上，人不多，可以慢慢品味。海军展览室里有完整的航空母舰模型，耗时11年打造，精细程度令人叹为观止。荧幕上展示的则是核心的喷气式起飞辅助装置，也是航母的核心技术之一。我看到的视频里有三条航道，每一条的发射时间大约间隔数分钟，所以估计下来平均一分钟能发射一架战斗机。我印象中还有更先进的电磁式辅助装置，能做到20秒发射一架，但可惜没能在展览中见识到。在二楼大厅的另一侧大屏幕上循环播放的则是发现者号最后一次发射的最后三分钟，你能看到人类迄今为止在航天发射上的最高成就，正如指令词中所说的，“the tribute of hard work and pride of the space team”. 我更感兴趣的展馆则被放在了二层中央，展示的是人类对于太阳系的探索。水金地火木土天海冥，每一个都是独特的存在，每一个都存在未解的谜团。而我每次看到类似的展出，也能收获一些此前不了解的知识，毕竟学海无涯。木星的磁层扰动冠绝太阳系，而且信号的长短分明，指引着截然不同的物理现象；海王星肉眼观察呈现的湛蓝色，是由于甲烷的存在；大行星的卫星越小越呈现出不规则的形状，甚至于近乎扁平的椭球体……联系之前才补充了一遍的潮水涨落和月球形状稳定性的定性解释，是不是觉得真正的知识都是相通的？

然而，总有不尽如人意的地方。误丢钱包一事，那群黑人安保人员的态度，让我异常愤怒。进门安检时，我把大衣和口袋里的钱包手机房卡放在了一起，收起来的时候钱包被卷入了大衣的帽子里却浑然不知。当我逛了近二十分钟发觉了一个很有意思的涡轮发动机想拍照时，才下意识地惊觉钱包不见了。第一反应当然是落在了安检处，于是我毫不犹豫地直接找了过去，却被几个黑人安保当作是没事儿找茬的人一般在哪儿冷嘲热讽。他们叫我去安保处，安保处的另外两个目光呆滞的黑人大叔更是一副要死不活的态度。那根本就不能叫失物招领处，那就是穷头陌路所。唯一态度比较好的是他们安保的头儿，能冷静的叫我再检查一遍随身的衣物，并告诉我他以往的经验。最后还是我自己找到的，脱下大衣翻了一遍，无意中看见了落在帽子里的黑色钱包。而那三个混蛋的安保，那句混账的“back off”，让我对美国的国民素质产生了切身的怀疑。都有耳闻过美国首府的乱，而一般提到美国治安之乱，往往都脱不开黑人数量之多。华盛顿的中心区便是如此，你能看见的酒店前台、星巴克服务员、博物馆安保，清一色全是黑人兄弟姐妹。我宁愿称之为断裂的美国文化，堂堂自诩世界第一大国，华府之下的国家博物馆安保也如此不堪。我并非指责所有的黑人群体，而恰恰相反，我指责更多的造成这一切的“纯种”美国人。黑人是美国种族歧视中被压迫的代表，他们的或过激或懒散的反应都是在夹缝般的生存空间中孕育出来的。在曼哈顿的小巷中迷路也有黑人大哥主动帮我指路，在华盛顿的酒店附近找门也有黑人小姐姐帮忙指引。当你看到一群如同僵尸般的黑人安保人员时，你不会埋怨某一个人——这是一个群体的代表。回到事件本身，我只是笃定钱包是在过安保的时候丢的，玻璃心的工作人员显然把这当成了我对他们的刁难，认为他们偷窃了我的钱包。不解决事情而选择上纲上线，人有时候就会有种种不理智的行为。

还记得电影《水形物语》中的黑人清洁大妈吗？人可以生活得辛苦，但这不妨碍我们有良知和热心肠。

又仔细逛了一次自然历史博物馆。哺乳动物三要素：hair, milk, earbone。人类不可思议的进化，脑容量突然增长的时间与气候变冷存在高度相关性。人类的祖先究竟是什么仍然是个谜。生物之间的基因相似度远高于想象：人与猿有98.5%；与猩猩有98%；与老鼠有90%；就连香蕉树，都有70%。而现今地球上任意两个人之间的基因相似度，则高达99.9%。究竟是什么成就了每个独一无二的个体？西非某个念不出名字的古老村落站在历史与现代的交汇点上何去何从，整个非洲大陆的现代化何去何从，都是巨大的问题。霸王龙骨架的复原、体重的估计、运动的方针、速度的估算，自然与科技的成就相映成辉。那毒蛇下颚处独特的突出骨架结构；那苍蝇蚊子蝴蝶的嘴部构造；那些巧夺天工的自然奇景……我喜欢这里。

排队进场的时候，一位亚裔美国女士开起了随行的法国人的玩笑。排队示意谦让，被“嘲讽”为虚伪；先生问博物馆里能否饮酒，被数落脑子里全是酒精。法国最近国内不太平，又是恐怖分子杀人，又是全国性的游行，但依旧改不了法国人骨子的浪漫洒脱。我们区分人不应依据肤色人种，而应依据文化渊源。如此来看，即便未来的法国“黑化”，他骨子里仍然会是法国。

# 杂谈闲侃

英国人果然是走在世界平等的最前沿。跨性别的认知并不妨碍人们成为杰出的科研工作者。

科学家的耻辱，就是Collison。 阿谀奉承，避而不答，问东答西，敷衍其辞。他根本没有做科学家的基本素质。

午餐时跟偶遇的美国大叔聊天，是今天最有意思的事情。他已白发苍苍，约莫耳顺年纪，是Boulder的一位系统控制工程师，第一次来AGU，曾在Boeing待过，也做过大型的望远镜项目。我跟他聊我的见解体会，他会用委婉而礼貌的方式举出例子来反驳；我跟他聊人工智能技术，他也会拿出身边的例子相互印衬；我跟他聊中美技术和体制差别，他也会站在理智民众的立场上看待中国的技术崛起。我喜欢跟陌生人聊天，何况是如此的主动而温和的长者。

普林斯顿的模拟组，有历史渊源，也有中流砥柱。说起来，Gabor不也是普林出来的嘛。百万行代码之上成就专家，我服。

如果你没能用一个简单清晰的例子来讲述你要说的东西，就说明你还没有真的懂。——张首晟
人生要做一点大事，要追求从根本上解决问题的理论和彻底颠覆游戏规则的技术，而不是在旧框架里修修补补。

张首晟用了一个圣诞假期搞明白的区块链，我又要用多久呢？显然我现在还是没有真正明白。

看到一个对硬件线程和软件线程的类比，我觉得茅塞顿开。硬件线程好比泳道，软件线程好比泳者。当人决定要游到对岸去时，会首先选择/被分配一条泳道；如果前方存在障碍，那么他还可能切换泳道；如果是一个团队比赛，那么多位选手平行分配会使团队时间更少。

孟醒师姐身上，带着中国古典女性的安静和典雅。同门师姐，我第一次见，便觉得世间竟有如此美好。安欣师兄，第二次见，微信头像写着洛伦兹公式，对各种波动如数家珍，非常厉害，非常欣赏。

做出更好的可视化效果图，就要抛弃过时的传统。这次还听说有GPU渲染（render）的动画技术，用Paraview做的，非常有兴趣。

大红袍味道相当不错，名不虚传。点菜的师傅很江湖很老道，最后的成品也不错，就是口重了些。

彭烨和冠宁的暧昧举动，基本说明他们成了。虽然没有什么言语上的直接交流，但是通过肢体语言同样可以说明问题。彭烨是个文静的好姑娘。庞冠宁这个老混蛋，原来早就喜欢她了吧。一切皆不是无中生有：命中有时终须有，命里无时莫强求。

Tamas不知所云的演讲，不知道他自己是否真的弄明白了。但更关键的，是看到真正干事的人。杨晨师姐很厉害。

第二次AGU，有了更多的收获。最主要的，就是认定了自己想做什么。我不懂的东西那么多，我不能把我的事情也那么多。但总有我明白的，真正掌握的，以及对于未知的鉴别力。吾之所向，一往无前：做出顶级的模拟，设计顶级的架构。

会议结束的晚上，我竟然失眠了。脑海中盘旋了无数的想法，仿佛就要爬起来直接把它们变为现实，想法清醒得很，却奈何眼睛实在撑不住。开完会让我感到兴奋而不是疲惫，是一个好的征兆。

回密歇根的航班，经历了人生中最刺激的气流颠簸。纵然我再知道现代民航客机的安全性，身体对于外界剧烈变化的反应是隐藏不住的。手心里冒的汗，椅子脚上蹬直的脚板，邻座美国妹子双手紧握双目合十的神态……肉眼可见的机翼的抖动，以及急速下坠时的失重感。由于异常的气流，飞机不得不在几分钟内从3500迈下降到2000迈，我们一行也算是用生命体验自然的扰动。我感到自己仿佛就是空间中的粒子，乘在介于波动和不稳定性的作用之中，随着曲线极速起伏。那跟任何的过山车都不能比：因为你不能预测接下来会发生什么，震荡何时消失，没有所谓的轨迹和终点。但稳下来后会涌出强烈的对比，平滑和激变间的界限竟然是这么分明，这么直观。我满脑子都是这些天看到的那一条条抖动的曲线：那一刻它们不是死的，而是活的。
真是有意思。在我对着笔记本正思考着如何处理电磁波的模拟时，一切突如其来。在晃动中我一把接住了滑落桌板的电脑，顺手塞进了书包，思忖着，可不要是我最后一次写Matlab。爱得深沉，最新敲的几行代码还没存呢，可不能就这样。

终究是一个理性的、感性的、乐观的人。
