---
title: Lyrics Collection
author: "Hongyang Zhou"
date: "2020-06-29"
categories: [music]
date-modified: "2024-05-03"
---

## 漫步人生路

在你身边路虽远未疲倦 伴你漫行一段 接一段

越过高峰 另一峰却又见 目标推远 让理想永运在前面

路纵崎岖亦不怕受磨练 愿一生中苦痛快乐也体验

愉快悲哀在身边转又转 风中赏雪雾里赏花快乐回旋

毋庸计较 快欣赏身边美丽每一天

还愿确信美景良辰 在脚边

愿将欢笑声盖掩苦痛那一面

悲也好 喜也好 每天找到新发现

让疾风吹呀吹 尽管给我俩考验

小雨点 放心洒 早就决心向着前

## 画

爱情就像蓝蓝天上，一片留白有你陪我想象

白马突然不再抽象，青蛙终于遇见灰姑娘

就算路还漫长，我却有一种预感，我相信这灵感

生活就像茫茫海上，一只小船勇敢乘风破浪

而你就像不远前方，默默张开双手的港湾

就算路还漫长，我却有一种预感，我相信这灵感

我把你画成花，未开的一朵花，再把思念一点一滴画成雨落下

每当我不在，请记得我的爱，就在同一天空之下遥远地灌溉

等待秋去春来，等待下一次花开，在咫尺的未来

爱情就像遥遥路上一束明亮却温柔的月光

快乐原来如此简单，你在身旁就是我的天堂

## 倾城

热情就算 熄灭了 分手这一晚 也重要

甜言蜜语 谎话嬉笑 都给我一点 不要缺少

话题尽了 也不紧要 吻我至凄冷的深宵

繁华都市 灯光普照 然而共你 已再没破晓

红眼睛 幽幽的看着这孤城 如同苦笑 挤出的高兴

全城为我 花光狠劲 浮华盛世 作分手布景

传说中 痴心的眼泪会倾城 霓虹熄了 世界渐冷清

烟花会谢 笙歌会停 显得这故事尾声 更动听

红眼睛 幽幽的看着这孤城 如同苦笑 挤出的高兴

琼楼玉宇 倒了阵形 来营造这 绝世的风景

传说中 痴心的眼泪会倾城 霓虹熄了 世界渐冷清

烟花会谢 笙歌会停 显得这故事尾声 更动听

## 成都

让我掉下眼泪的，不止昨夜的酒

让我依依不舍的，不止你的温柔

余路还要走多久，你攥着我的手

让我感到为难的，是挣扎的自由

分别总是在九月，回忆是思念的愁

深秋嫩绿的垂柳，亲吻着我额头

在那座阴雨的小城里，我从未忘记你

成都，带不走的，只有你

和我在成都的街头走一走 喔…

直到所有的灯都熄灭了也不停留

你会挽着我的衣袖，我会把手揣进裤兜

走到玉林路的尽头，坐在小酒馆的门口


## 声声慢

青砖伴瓦漆，白马踏新泥

山花蕉叶暮色丛染红巾

屋檐洒雨滴，炊烟袅袅起

蹉跎辗转宛然的你在哪里

寻寻觅觅，冷冷清清

月落乌啼月牙落孤井

零零碎碎，点点滴滴

梦里有花梦里青草地

长发引涟漪,白布展石矶

河童撑杆摆长舟渡古稀

## 梦里水乡

春天的黄昏，请你陪我到梦中的水乡。让挥动的手在薄雾中飘荡。

不要惊醒杨柳岸，那些缠绵的往事；化作一缕轻烟，已消失在远方。

暖暖的午后，闪过一片片粉红的衣裳。谁也载不走那扇古老的窗。

玲珑少年在岸上，守候一生的时光：为何没能做个，你盼望的新娘？

淡淡相思都写在脸上，沉沉离别背在肩上。泪水流过脸庞，所有的话， 现在还是没有讲。

看那青山荡漾在水上，看那晚霞吻着夕阳。我用一生的爱，去寻找那一个家，今夜你在何方。

转回头迎着你的笑颜，心事全都被你发现。梦里遥远的幸福，它就在我的身旁。

## 祝你一路顺风

那一天知道你要走

我们一句话也没有说

当午夜的钟声敲痛离别的心门

却打不开我深深的沉默

那一天送你送到最后

我们一句话也没有留

当拥挤的月台挤痛送别的人们

却挤不掉我深深的离愁

我知道你有千言你有万语，却不肯说出口

你知道我好担心我好难过，却不敢说出口

当你背上行囊，卸下那份荣耀

我只能让眼泪留在心底

面带着微微笑，用力的挥挥手

祝你一路顺风

当你踏上月台，从此一个人走

我只能深深的祝福你

深深的祝福你，最亲爱的朋友

## 暧昧

眉目里似哭不似哭

还祈求甚么说不出

陪著你轻呼著烟圈

到唇边讲不出满足

你的温柔怎可以捕捉

越来越近却从不接触

茶没有喝光早变酸

从来未热恋已失恋

陪著你天天在兜圈

那缠绕怎么可算短

你的衣裳今天我在穿

未留住你却仍然温暖

徘徊在似苦又甜之间

望不穿这暧昧的眼

爱或情借来填一晚

终须都归还无谓多贪

犹疑在似即若离之间

望不穿这暧昧的眼

似是浓却仍然很淡

天早灰蓝想告别

偏未晚

## 追光者

如果说 你是海上的烟火 我是浪花的泡沫 某一刻 你的光照亮了我

如果说 你是遥远的星河 耀眼得让人想哭 我是追逐着你的眼眸 总在孤单时候眺望夜空

我可以跟在你身后 像影子追着光梦游 我可以等在这路口 不管你会不会经过

每当我为你抬起头 连眼泪都觉得自由 有的爱像阳光倾落 边拥有边失去着

如果说 你是夏夜的萤火 孩子们为你唱歌 那么我 是想要画你的手

你看我 多么渺小一个我 因为你有梦可做 也许你不会为我停留 那就让我站在你的背后

我可以跟在你身后 像影子追着光梦游 我可以等在这路口 不管你会不会经过 每当我为你抬起头

连眼泪都觉得自由 有的爱像大雨滂沱 却依然相信彩虹

我可以跟在你身后 像影子追着光梦游 我可以等在这路口 不管你会不会经过

每当我为你抬起头 连眼泪都觉得自由 有的爱像大雨滂沱 却依然相信彩虹

## 倩女幽魂

人生路美梦似路长  路里风霜风霜扑面干

红尘里美梦有几多方向  找痴痴梦幻中心爱路随人茫茫

人生是百美梦与热望  梦里依稀依稀有泪光

何从何去去觅我心中方向  风仿佛在梦中轻叹路和人茫茫

人间路快乐少年郎  路里崎岖崎岖不见阳光

泥尘里快乐有几多方向  一丝丝梦幻般风度雨路随人茫茫

丝丝梦幻般风雨路随人茫茫

## 望乡

夕阳河边走 举目望苍穹

缈缈炊烟飘来了思乡愁

多少回朝夕晨暮思念着你呦

淼淼河水是我流淌的泪

窗外明月光 映照我脸庞

欲知故乡亲人是否安康

捧一盏乡酒陪伴着你呦

无论我身在他乡与远方

给你我的喜与悲

不止为那山与水

分不清是梦与醒

忘不掉是你身影

穿过岁月春与秋

尝尽世间爱与愁

何故此时别离与拥有

## 归乡

运河的舟楫 南来北望

千折百回过长江

北固楼遥望 西津渡的过往

看不尽满眼风光

焦山烟雨 洒落幽幽江南

明月何时照我还

风涛千万里 金山水连天

却似江心一朵莲

南来的风 东去的水

浮云伴着游子归

西窗的雨 归来的你

醉在故乡斜月里

## 浣溪沙

谁道飘零不可怜 旧游时节好花天

谁道飘零不可怜 断肠人去自经年

一片晕红才着雨 几丝柔绿乍和烟

倩魂销尽夕阳前 当时只道是寻常

已惯天涯莫浪愁 寒云衰草渐成秋

已惯天涯莫浪愁 漫因睡起又登楼

伴我萧萧惟代马 笑人寂寂有牵牛

已惯天涯莫浪愁 劳人只合一生休

残雪凝辉冷画屏 落梅横笛已三更

更无人处月胧明

我是人间惆怅客 知君何事泪纵横

断肠声里忆平生

谁念西风独自凉 萧萧黄叶闭疏窗

谁念西风独自凉 沉思往事立残阳

被酒莫惊春睡重 赌书消得泼茶香

谁念西风独自凉 当时只道是寻常

## 一程山水一程歌

是我将愁耽成醉醒做睡 还是愁与我的心共已累

非我赋诗诗赋我 非我饮酒酒饮我

何时撷身竟已沾上苍苔冷

世上何物最易催少年老

半是心中积霜半是人影杳

非我离月月离我 非我思乡乡思我

归得昔日桥边红药不识人

究竟是我走过路 还是路正走着我

风过西窗客渡舟船无觅处

是我经过春与秋 还是春秋经过我

年年一川新草遥看却似旧

夜深孤灯照不悔

回首青江尽是泪

风情拍肩怕见明月减青辉

一程山水一程歌 一笛疏雨寒吹彻

梦在夜夜深深尽处轻轻和

## 牵手

因为爱着你的爱 因为梦着你的梦

所以悲伤着你的悲伤 幸福着你的幸福

因为路过你的路 因为苦过你的苦

所以快乐着你的快乐 追逐着你的追逐

因为誓言不敢听 因为承诺不敢信

所以放心着你的沉默 去说服明天的命运

没有风雨躲得过 没有坎坷不必走

所以安心的牵你的手 不去想该不该回头

也许牵了手的手 前生不一定好走

也许有了伴的路 今生还要更忙碌

所以牵了手的手 来生还要一起走

所以有了伴的路 没有岁月可回头

## 荷塘月色

剪一段时光缓缓流淌

流进了月色中微微荡漾

弹一首小荷淡淡的香

美丽的琴音就落在我身旁

萤火虫点亮夜的星光

谁为我添一件梦的衣裳

推开那扇心窗远远地望

谁采下那一朵昨日的忧伤

我像只鱼儿在你的荷塘

只为和你守候那皎白月光

游过了四季荷花依然香

等你宛在水中央

## 蝴蝶泉边

我看到满片花儿的开放 隐隐约约有声歌唱

开出它最灿烂笑的模样 要比那日光还要亮

荡漾着清澄流水的泉啊 多么美丽的小小村庄

我看到淡淡飘动的云儿 印在花衣上

我唱着妈妈唱着的歌谣 牡丹儿绣在金匾上

我哼着爸爸哼过的曲调 绿绿的草原上牧牛羊

环绕着扇动银翅的蝶啊 追回那遥远古老时光

传诵着自由勇敢的鸟啊 一直不停唱

叶儿上轻轻跳动的水花 偶尔沾湿了我发梢

阳光下那么奇妙的小小人间 变模样

## 如果云知道

爱一旦结冰 一切都好平静

泪水它一旦流尽 只剩决心

放逐自己在黑夜的边境 任由黎明一步一步向我逼近
　　
想你的心 化成灰烬

真的有点累了 没什么力气

有太多太多回忆 哽住呼吸

爱你的心我无处投递 如果可以飞檐走壁找到你
　　
爱的委屈不必澄清 只要你将我抱紧

如果云知道 想你的夜慢慢熬

每个思念过一秒 每次呼喊过一秒

只觉得生命不停燃烧

如果云知道 逃不开纠缠的牢

每当心痛过一秒 每回哭醒过一秒

只剩下心在乞讨 你不会知道

## 知否知否

一朝花开傍柳 寻香误觅亭侯

纵饮朝霞半日晖 风雨着不透

一任宫长骁瘦 台高冰泪难流

锦书送罢蓦回首 无余岁可偷

昨夜雨疏风骤 浓睡不消残酒
试问卷帘人 却道海棠依旧
知否 知否 应是绿肥红瘦

昨夜雨疏风骤 浓睡不消残酒
试问卷帘人 却道海棠依旧
知否 知否 应是绿肥红瘦

## 一絲不掛

分手時內疚的你一轉臉

為日後不想有甚麼牽連

當我工作睡覺禱告娛樂那麼刻意過好每天

誰料你見鬆綁了又願見面

誰當初想擺脫被圍繞左右

過後誰人被遙控於世界盡頭

勒到呼吸困難才知變扯線木偶

這根線其實說到底 誰拿捏在手

不聚不散 只等你給另一對手擒獲

那時青絲 不會用上餘生來量度

但我拖著軀殼 發現沿途尋找的快樂

仍繫於你肩膊 或是其實在等我捨割

然後斷線風箏會直飛天國

這些年望你緊抱他出現

還憑何擔心再互相糾纏

給我找個伴侶找到留下你的足印也可發展

全為你背影逼我步步向前

如一根絲牽引著拾荒之路

結在喉嚨內痕癢得似有還無

為你安心我在微笑中想吐未吐

只想你和伴侶要好才頑強病好

不聚不散 只等你給另一對手擒獲

以為青絲 不會用上餘生來量度

但我拖著軀殼 發現沿途尋找的快樂

仍繫於你肩膊 或是其實在等我捨割

然後斷線風箏會直飛天國

一直不覺 綑綁我的未可扣緊承諾

滿頭青絲 想到白了仍懶得脫落

被你牽動思覺 最後誰願纏繞到天國

然後撕裂軀殼 欲斷難斷在 不甘心去捨割

難道愛本身可愛在於束縛

無奈你我牽過手 沒繩索

## 岁月如歌

爱上了看见你如何不懂谦卑

去讲心中理想不会俗气

犹如看得见晨曦才能欢天喜地

抱着你我每次回来多少惊喜

也许一生太短陪着你

情感有若行李仍然沉重待我整理


再见了背向你眉头多少伤悲

也许不必再讲所有道理

何时放松我自己才能花天酒地

抱着你我说过如何一起高飞

这天只想带走还是你

如重温往日邮寄但会否疲倦了嬉戏


天气不似预期但要走总要飞

道别不可再等你不管有没有机

给我体贴入微但你手如明日便要远离

愿你可以留下共我曾愉快的忆记

当世事再没完美可远在岁月如歌中找你

## K歌之王

我唱得不夠動人你別皺眉 我願意和你約定至死

我只想嬉戲唱遊到下世紀 請你別嫌我將這煽情奉獻給你

還能憑甚麼？擁抱若未能令你興奮 便宜地唱出 寫在情歌的性感

還能憑甚麼？要是愛不可感動人 俗套的歌詞 煽動你惻忍

誰人又相信一世一生這膚淺對白 來吧送給你叫幾百萬人流淚過的歌

如從未聽過誓言如幸福摩天輪 才令我因你要呼天叫地愛愛愛愛那麼多

將我漫天心血一一拋到銀河 誰是垃圾 誰不捨我難過 分一丁目贈我

我唱出心裡話時眼淚會流 要是怕難過抱住我手

我只得千語萬言放在你心 比渴望地老天荒更簡單未算罕有

誰人又相信一世一生這膚淺對白 來吧送給你叫幾百萬人流淚過的歌

如從未聽過誓言如幸福摩天輪 才令我因你要呼天叫地愛愛愛愛那麼多

給你用力作二十首不捨不棄 還附送你愛得過火

給你賣力唱二十首真心真意 米高峰都因我動容

無人及我 你怎麼竟然說K歌之王 是我

我只想跟你未來浸在愛河 而你那呵欠絕得不能絕 絕到溶掉我

## 青城山下白素贞

青城山下白素贞 洞中千年修此身

勤修苦练来得道 脱胎换骨变成人

一心向道无杂念 皈依三宝弃红尘

望求菩萨来点化 渡我素贞出凡尘

## 地厚天高

地有多厚天有多高，地有多厚天有多高

星星眨着眼月儿划问号，彗星拖着长长的尾巴

彩虹来架桥，时光在飞逝

生命知多少，风儿吹起朵朵浪花

太阳开口笑，哦哦只要你爱想爱问爱动脑

天地间奇妙的问题你全明了，哦只要你爱想爱问爱动脑

天地间奇妙的问题你全明了

## 不老的传说

流传在月夜那故事

当中的主角极漂亮

如神话活在这世上

为世间不朽的爱轻轻唱


若是你共情人 热切信有爱

永远真挚地 投入这个梦乡

合着两眼定能遇见那爱侣

给你讲出永不老那点真相

徘徊夜里时常亦听到歌颂

真爱总会是永远

谁人亦会 重拾逝去了的梦

在星辉闪闪午夜 飘于晚空

流传在月夜那故事

将星光深处亦照亮

如神话活在这世上

为你将不朽的爱轻轻唱


遇着故事内描述那对爱侣

永远不老地游在每个梦乡

日夜变换未能换却那季节

因那心中爱坚固永不转向

无人夜里 铉乐在远远歌颂

真爱总会是永远

人成熟了 仍然被暗暗牵动

伴星辉跟恋爱梦 深深抱拥

## 那女孩对我说

心很空 天很大 雲很重 我恨孤單 卻趕不走

捧著她的名字 她的喜怒哀樂 往前走 多久了

一個人心中只有一個寶貝 久了之後 她變成了眼淚

淚一滴在左手 凝固成為寂寞 往回看 有什麼

那女孩對我說 說我保護她的夢

說這個世界 對她這樣的不多

她漸漸忘了我 但是她並不曉得

遍體鱗傷的我 一天也沒再愛過

那女孩對我說 說我是一個小偷

偷她的回憶 塞進我的腦海中

我不需要自由 只想揹著她的夢

一步步向前走 她給的永遠 不重

## 如果当时

为什么 你当时对我好 又为什么 现在变得冷淡了

我知道 爱要走难阻挠 反正不是我的 我也不该要

你和我 曾经有共同爱好 谁的耳边 总有绝句在萦绕

我们俩 用文言文对话真的很搞笑 还笑那曹操贪慕着小乔

天灰了 雨坠了 视线要模糊了 此时感觉到你的重要

爱走了 心走了 你说你要走了 我为你唱最后的古谣

红雨瓢泼泛起了回忆怎么潜 你美目如当年 流转我心间

渡口边最后一面洒下了句点 与你若只如初见 何须感伤离别

## 半生雪

霜月落庭前 照谁一夜无眠 提笔惊扰烛火 回忆难写

看人间故事 都逃不过离别 数不完的阴晴换圆缺

半生风雪 吹不散花落时节的眼泪

唤不回 孤雁终要南飞

心事谁了解 唯有明月来相随

思念予我眉间又几分憔悴

半生风雪 吹不散岁月留下的眼泪

换不回 青丝已尽成灰

结局谁来写 写不完爱恨缠绵

徒我顾影自怜自叹又几遍

## 沧海一声笑

滄海一聲笑 滔滔兩岸潮

浮沉隨浪 只記今朝

蒼天笑 紛紛世上潮

誰負誰勝出 天知曉

江山笑 煙雨遙

濤浪淘盡紅塵俗世幾多嬌

清風笑 竟惹寂寥

豪情還剩了一襟晚照

蒼生笑 不再寂寥

豪情仍在痴痴笑笑

## 最初的梦想

如果骄傲没被现实大海冷冷拍下 又怎会懂得要多努力 才走得到远方

如果梦想不曾坠落悬崖千钧一发 又怎会晓得执着的人 拥有隐形翅膀

把眼泪种在心上 会开出勇敢的花

可以在疲惫的时光 闭上眼睛闻到一种芬芳

就像好好睡了一夜直到天亮 又能边走着边哼着歌 用轻快的步伐

沮丧时总会明显感到孤独的重量

多渴望懂得的人给些温暖借个肩膀

很高兴一路上 我们的默契那么长

穿过风又绕了弯 心还连着像往常一样

最初的梦想紧握在手上 最想要去的地方 怎么能在半路就返航

最初的梦想绝对会到达 实现了真的渴望 才能够算到过了天堂

## 这世界那么多人

这世界有那么多人 人群里 敞着一扇门

我迷朦的眼睛里长存 初见你 蓝色清晨

这世界有那么多人 多幸运 我有个我们

这悠长命运中的晨昏 常让我 望远方出神

灰树叶飘转在池塘 看飞机轰的一声去远乡

光阴的长廊 脚步声叫嚷 灯一亮 无人的空荡

晚风中闪过 几帧从前啊 飞驰中旋转 已不见了吗

远光中走来 你一身晴朗 身旁那么多人 可世界不声 不响

笑声中浮过 几张旧模样 留在梦田里 永远不散场

暖光中醒来 好多话要讲 世界那么多人 可是它不声 不响

这世界有那么个人 活在我 飞扬的青春

在泪水里浸湿过的长吻 常让我 想啊想出神

## 梦醒时分

你说你爱了不该爱的人，你的心中满是伤痕。

你说你犯了不该犯的错，心中满是悔恨。

你说你尝尽了生活的苦，找不到可以相信的人。

你说你感到万分沮丧，甚至开始怀疑人生。

早知道伤心总是难免的，你又何苦一往情深？

因为爱情总是难舍难分，何必在意那一点点温存。

要知道伤心总是难免的，在每一个梦醒时分。

有些事情你现在不必问，有些人你永远不必等。

## 旅行的意义

你看过了许多美景 你看过了许多美女

你迷失在地图上每一道短暂的光阴

你品尝了夜的巴黎 你踏过下雪的北京 你熟记书本里每一句你最爱的真理

却说不出你爱我的原因 却说不出你欣赏我哪一种表情

却说不出在什么场合我曾让你动心 说不出离开的原因

你累积了许多飞行 你用心挑选纪念品

你收集了地图上每一次的风和日丽

你拥抱热情的岛屿 你埋葬记忆的土耳其 你留恋电影里美丽的不真实的场景

却说不出你爱我的原因 却说不出你欣赏我哪一种表情

却说不出在什么场合我曾让你分心 说不出旅行的意义

你勉强说出你爱我的原因 却说不出你欣赏我哪一种表情

却说不出在什么场合我曾让你动心 说不出旅行的意义

勉强说出你为我寄出的每一封信 都是你离开的原因

你离开我 就是旅行的意义

## 怎叹

唱一首水调歌头 那明月何时能有

我站在梧桐树下 期待你回眸

若今生牵你的手 又哪怕岁月悠悠

只盼那清风依旧 与你长相守

散不去只剩温柔 这秋风吹去离愁

只感叹浮生若梦 无人在身后

抬头看梨花翩翩 是谁在独自承受

怎奈何蓦然回首 你皱起眉头

怎叹呐山有木兮那木有枝 心悦君兮啊君不知

可是前世与你错过太多事 怎叹呐秋有月兮那月有诗

也不及与你相守时 梦里与你山水再相识

## 原來你也在這裡

請允許我塵埃落定 用沉默埋葬了過去

滿身風雨我從海上來 才隱居在這沙漠裡

該隱瞞的事總清晰 千言萬語只能無語

愛是天時地利的迷信 喔 原來你也在這裡

啊 那一個人 是不是只存在夢境裡

為什麼我用盡全身力氣 卻換來半生回憶

若不是你渴望眼睛 若不是我救贖心情

在千山萬水人海相遇 喔 原來你也在這裡

## 我的果汁分你一半

我要那个那个那个 那个那个那个 那个那个那个啊

你要那个那个那个 那个那个那个 那个那个那个啊

月亮弯弯 绵绵绵绵缠缠 果汁分你一半 爱相互分担

长路漫漫磕磕磕磕绊绊 果汁分你一半 爱相互扶搀

今晚多么美满 约会相当浪漫 我果汁分你一半

我结账你买单谁跟谁别细算 我果汁分你一半

偶尔我也会烦 脸色说翻就翻 我果汁分你一半

就算怎么艰难也要保持乐观 我果汁分你一半

当习惯成自然 一个眼神交换 我果汁分你一半

我吃饭你刷碗 不是我要偷懒 我果汁分你一半

偶尔你也会乱 发脾气不敢管 我果汁分你一半

向前向后攻占 粘我阴魂不散 我果汁分你一半

## 月光

哦 月光洒在每个人心上 让回家的路 有方向

哦 离开太久的故乡 和老去的爹娘

哦 迎着月色散落的光芒 把古老的歌谣 轻轻唱

哦 无论走到任何的地方 都别忘了故乡

是什么力量 让我们坚强

是什么离去 让我们悲伤

是什么付出 让我们坦荡

是什么结束 让我们成长

是什么誓言 让我们幻想

是什么距离 让我们守望

是什么欲望 让我们疯狂

是什么风雨 让我们流浪

哦 月亮高高挂在了天上 为回家的人 照着亮

哦 离开太久的故乡 快快回去见爹娘

## 大鱼

海浪无声将夜幕深深淹没 漫过天空尽头的角落

大鱼在梦境的缝隙里游过 凝望你沉睡的轮廓

看海天一色 听风起雨落 执子手吹散苍茫茫烟波

大鱼的翅膀 已经太辽阔 我松开时间的绳索

怕你飞远去 怕你离我而去 更怕你永远停留在这里

每一滴泪水 都向你流淌去 倒流进天空的海底

看你飞远去 看你离我而去 原来你生来就属于天际

每一滴泪水 都向你流淌去 倒流回最初的相遇

## 相思

红豆生南国 是很遥远的事情

相思算什么 早无人在意

醉卧不夜城 处处霓虹

酒杯中好一片滥滥风情

最肯忘却古人诗

最不屑一顾是相思

守着爱怕人笑 还怕人看清

春又来看红豆开 竟不见有情人去采

烟花拥着风流真情不在

## 情人

盼望你没有为我又再渡暗中淌泪

我不想留底 你的心空虚

盼望你别再让我象背负太深的罪

我的心如水 你不必痴醉

盼望我别去后会共你在远方相聚

每一天望海 每一天相对

盼望你现已没有让我别去的恐惧

我即使离开 你的天空里

哦 你可知谁甘心归去 你与我之间有谁

是缘是情是童真 还是意外

有泪有罪有付出 还有忍耐

是人是墙是寒冬 藏在眼内

有日有夜有幻想 没法等待

多少春秋风雨改 多少崎岖不变爱 多少唏嘘的你在人海

## 在水一方

绿草苍苍 白雾茫茫

有位佳人 在水一方

绿草萋萋 白雾迷离

有位佳人 靠水而居

我愿逆流而上 依偎在她身旁

无奈前有险滩 道路又远又长

我愿顺流而下 找寻她的方向

却见依稀仿佛 她在水的中央

我愿逆流而上 与她轻柔细语

无奈前有险滩 道路曲折无已

我愿顺流而下 找寻她的踪迹

却见仿佛依稀 她在水中伫立

绿草苍苍 白雾茫茫

有位佳人 在水一方

## 一路生花

海上的晚霞像年少的畫 鋪在天空等海鷗銜走它

遙遠的帆任風浪拍打 為夢再痛也不會害怕

遠走的風沙去誰的天涯 春天可曾在哪裡見過他

時間的手撫過了臉頰 他們誰都沉默不說話

我希望許過的願望一路生花 護送那時的夢抵擋過風沙

指尖的櫻花如詩寫誰的韶華 瘋狂的熱愛夾帶著文雅

我希望許過的願望一路生花 將那雨中的人藏在屋簷下

歲月在沖刷逆流滄桑的喧嘩 安靜的夜晚你在想誰嗎

## 漠河舞厅

我从没有见过极光出现的村落 也没有见过有人 在深夜放烟火

晚星就像你的眼睛杀人又放火 你什么都没有说 野风惊扰我

三千里 偶然见过你 花园里 有裙翩舞起

灯光底 抖落了晨曦 在1980的漠河舞厅


可是你 惹怒了神明 让你去 还那么年轻

都怪你 远山冷冰冰 在一个人的漠河舞厅


如果有时间 你会来看一看我吧

看大雪如何衰老的 我的眼睛如何融化

如果你看见我的话 请转过身去再惊讶

我怕我的眼泪 我的白发像羞耻的笑话

如果有一天 我的信念忽然倒塌

城市的花园没有花 广播里的声音嘶哑

如果真有这天的话 你会不会奔向我啊

尘封入海吧 尘封入海吧

## 孤独患者

欢笑声　欢呼声 炒热气氛　心却很冷

聚光灯　是种蒙恩 我却不能　喊等一等

我真佩服我　还能幽默 掉眼泪时　用笑掩过

怕人看破　顾虑好多 不谈寂寞　我们就都快活


笑越大声　越是残忍 挤满体温　室温更冷

万一关灯　空虚扰人 我却不能　喊等一等

你说你爱我　却一直说 说我不该　窝在角落

策划逃脱　这也有错 连我脆弱　的权利都掠夺


我不唱声嘶力竭的情歌 不表示没有心碎的时刻

我不曾摊开伤口任宰割 愈合　就无人晓得　我内心挫折

活像个孤独患者　自我拉扯 外向的孤独患者　有何不可

我不要声嘶力竭的情歌 来提示我需要你的时刻

表面镇定并不是保护色 反而　是要你懂得　我不知为何

活像个孤独患者　自我拉扯 外向的孤独患者　需要认可

## 你

你 从天而降的你 落在我的马背上

如玉的模样 清水般的目光 一丝浅笑让我心发烫

你 头也不回的你 展开你一双翅膀

寻觅著方向 方向在前方 一声叹息将我一生变凉

你在那万人中央 感受那万丈荣光

看不见你的眼睛 是否会藏着泪光

我没有那种力量 想忘也终不能忘

只等到漆黑夜晚 梦一回那曾经心爱的姑娘

## 囚鸟

我是被你囚禁的鸟 已经忘了天有多高

如果离开你给我的小小城堡 不知还有谁能依靠

我是被你囚禁的鸟 得到的爱越来越少

看着你的笑在别人眼中燃烧 我却要不到一个拥抱

我像是一个你可有可无的影子 冷冷的看着你说谎的样子

这撩乱的城市 容不下我的痴 是什么让你这样迷恋这样的放肆

我像是一个你可有可无的影子 和寂寞交换着悲伤的心事

对爱无计可施 这无味的日子 眼泪是唯一的奢侈

## 灰色轨迹

酒一再沉溺 何时麻醉我抑郁 过去了的一切会平息

冲不破墙壁 前路没法看得清 再有哪些挣扎与被迫

心一再回忆 谁能为我去掩饰 到哪里都跟你要认识

洗不去痕迹 何妨面对要可惜 各有各的方向与目的

踏着灰色的轨迹 尽是深渊的水影

我已背上一身苦困后悔与唏嘘 你眼里却此刻充满泪

这个世界已不知不觉的空虚 喔 不想你别去

## 铁血丹心

依稀往梦似曾见 心内波澜现

抛开世事断仇怨 相伴到天边

逐草四方沙漠苍茫 （冷风吹天苍苍）

哪惧雪霜扑面 （藤树相连）

射雕引弓塞外奔驰 （猛风沙野茫茫）

笑傲此生无厌倦 （藤树两缠绵）

天苍苍野茫茫万般变幻 （应知爱意似流水 斩不断理还乱）

身经百劫也在心间 恩义两难断

## 笑看风云

谁没有一些刻骨铭心事 谁能预计后果

谁没有一些旧恨心魔 一点点无心错

谁没有一些得不到的梦 谁人负你负我多

谁愿意解释为了什么 一笑已经风云过

活得开心心不记恨 为今天欢笑唱首歌

任胸襟吸收新的快乐 在晚风中敞开心锁

谁愿记沧桑匆匆往事 谁人是对是错

从没有解释为了什么 一笑看风云过

## 假如爱有天意

当天边那颗星出现 你可知我又开始想念

有多少爱恋只能遥遥相望 就像月光洒向海面

年少的我们曾以为 相爱的人就能到永远

当我们相信情到深处在一起 听不见风中的叹息

谁知道爱是什么 短暂的相遇却念念不忘

用尽一生的时间 竟学不会遗忘

如今我们已天各一方 生活得像周围人一样

眼前人给我最信任的依赖 但愿你被温柔对待

多少恍惚的时候 仿佛看见你在人海川流

隐约中你已浮现 一转眼又不见

短暂的相遇却念念不忘

多少恍惚的时候 仿佛看见你在人海川流

隐约中你已浮现 一转眼又不见

当天边那颗星出现 你可知我又开始想念

有多少爱恋今生无处安放 冥冥中什么已改变

月光如春风拂面

## 想见你

当爱情遗落成遗迹 用象形刻划成回忆

想念几个世纪 才是刻骨铭心

---

若能回到冰河时期 多想把你抱紧处理

你的笑多疗愈 让人生也苏醒

失去 你的风景 像座废墟 像失落文明

能否 一场奇迹 一线生机 能不能 有再一次 相遇

---

任时光更迭了四季 任宇宙物换或星移

永远不退流行 是青涩的真心

未来 先进科技 无法模拟 你拥抱暖意

如果 另个时空 另个身体 能不能 换另一种 结局

---

想见你 只想见你 未来过去 我只想见你

穿越了 千个万个 时间线里 人海里相依

用尽了 逻辑心机 推理爱情 最难解的谜

会不会 妳也 和我一样 在等待一句 我愿意

---

想见你 每个朝夕 想见你 每个表情

想穿越 每个平行 在未来 和过去 紧紧相依

想follow 每则IG 不错过 你的踪迹

会不会 你也一样 等待着那句 我愿意

## 其实都没有

从什么都没有的地方

到什么都没有的地方

我们 像没发生事一样

自顾地 走在路上

忘掉了的人只是泡沫

用双手轻轻一触就破

泛黄 有他泛黄的理由

思念将 越来越薄

你微风中浮现的 从前的面容

已被吹送到天空

我在脚步急促的城市之中

依然一个人生活

我也曾经憧憬过 后来没结果

只能靠一首歌真的在说我

是用那种特别干哑的喉咙

唱着淡淡的哀愁

我也曾经做梦过 后来更寂寞

我们能留下的其实都没有

原谅我用特别沧桑的喉咙

假装我很怀旧

假装我很痛

其实我真的很怀旧

而且也很痛

## Rhythm of the Rain

Listen to the rhythm of the falling rain

Telling me just what a fool I've been

I wish that it would go and let me cry in vain

And let me be alone again

The only girl I care about has gone away

Looking for a brand new start

But little does she know that when she left that day

Along with her she took my heart

Rain please tell me now does that seem fair

For her to steal my heart away when she don't care?

I can't love another when my hearts somewhere far away

Rain won't you tell her that I love her so

Please ask the sun to set her heart aglow

Rain in her heart and let the love we knew start to grow
