---
title: Computer Hardwares and Drivers
subtitle: 装机记录
author: "Hongyang Zhou"
date: "2025-08-17"
date-modified: "2025-10-07"
categories: [programming, hardware]
---

## 装机实录

第一次装机，记录一下过程。实践出真知。

上个月让表弟从舅舅那里拉过来一台主机，比较老的配置，好像是Intel 10代以前的四核CPU，2*8GB内存，加上GTX1060的GPU。折腾了一下，死活没接上显示，查了一下可能是内存条接触不良。心下一想，索性直接去配了一台新主机，并且参考了舅舅的意见，去掉了机械硬盘和GPU，避免第一次装多些额外的麻烦。做了一些功课，考虑CPU次旗舰，工作编程软件优先，以后升级空间，于是选定了以下配置：

1. CPU: Intel Core Ultra 7 265K Arrow Lake 20 core.这是15代，英特尔重新换了命名，颇为令人困惑。这一代为了降低功耗取消了超线程，8个性能核12个能效核。据说和前几代相比，能效核的性能大幅上升，并且没有缩缸风险。K说明自带核显，查了下性能大概略逊于主机上的1060。
2. Motherboard: ASUS Z890 AYW GAMING WIFI W Intel LGA 1851 ATX. 这个是和CPU捆绑销售的,价格合理，旗舰主板，做工精良。
3. Memory: G.Skill Ripjaws S5 2*16 GB DDR5-6000 PC5-48000。5代和4代似乎没什么速度差距，就是通道数目有些变化。现在的GPU里面的DDR好像编号都到6代了。内存现在非常便宜。本来考虑直接上64GB的，但想着反正一共四个插槽，先从32GB开始，要是觉得还有需求再去买两条就好了。
4. SSD: Samsung 990 EVO Plus 2TB V NAND. 固态硬盘都是三星的天下。
5. Power: MSI MAG A750GL 750 W ATX 3.1 Compatible。没有概念，本来在网上订的另外的店员，取货的店里刚好没有，于是店员就推荐了这一款，一样价，100刀。
6. Case: Lian Li O11 Vision Compact Tempered Glass ATX Mid Tower. 白色机箱，很宽，玻璃壳，外观很简洁干净。
7. Fan: Be Quiet PURE ROCK 3 CPU Air Cooler。简单挑了个40刀的中间价格。自带硅脂，无需再单独购入thermal paste。

以上这些加起来855刀，我觉得十分划算。考虑之后加一块5070的显卡，大概550刀。据说50系列销量不佳，之后还会降价，咱拭目以待。

整个硬件组装过程还是比较顺利的，顺序是CPU->memory->SSD->Fan->Case->Power。唯一就是接线的时候第一次少接了几根，第一次接电没点亮。重新接好了就没问题。真正麻烦的是软件。我预先购买了一块USB，在Ubuntu官网了拷了盘，25.04。结果装好了，没有Wifi驱动。一搜，首先网友盲推LTS版本Ubuntu 24，说是新版本可能不稳定。我于是又重新拷USB，装上了24——一样，还是没有Wifi选项。又搜了半天，看到一条记录是Linux目前没有该款主板的网卡驱动，说是太新。顿时非常郁闷，那就意味这无论装哪个Linux操作系统都会遇到一样的问题。没办法，只能转战Windows。没有单独买个人版，利用学校的微软账号从Azure上面弄到一个序列号，再学习了一下Win 11的U盘安装方法。这时之前用作Ubuntu系统的安装盘无法被Windows的安装拷贝程序识别。弄半天发现是需要手动格式化，先在图形界面操作，报错read-only。又看了一阵找到一个Windows自带的命令行程序能修改读写权限，搞了两遍终于格式化成功。然后拷贝程序顺利识别，拿着U盘再去新机器上刷掉Ubuntu装Win11。第一次尝试出现了GPT header corruption错误，可能是分区错误，要调整BIOS设置。又是个坑。折腾了好一圈，看到屏幕上的建议把Boot Sector Recovery Policy 从User变成了Auto，退出BIOS，电脑自己重启了几遍后成功进入Win11系统。然而，此时竟然依然没有Wifi驱动......我打开主板说明书，翻到了驱动安装的页面，扫描二维码，到ASUS的官网注册了这块主板，用笔记本下载了WLAN和Wifi的驱动到U盘，插回PC，安装。终于，几经折腾，下午一点半开始，晚上出去吃了个饭俩小时，回来接着断断续续看，直到晚上11点42分全部搞定。偏底层的部分没有经验，不知道驱动和兼容性是这么麻烦的环节。其实现在参考资料已经很多了，但没有动手前还是很难考虑周全。我要是会写驱动，那就是和真计算机科班出身的一样了。这本来也是操作系统里面十分麻烦的环节。目前仍有无线网卡和蓝牙的驱动问题没有解决。

剩下的软件安装都十分顺利，WSL2+Ubuntu、VSCode、Zsh、Python、Julia、SSH、ParaView，基本一次完成。

### GPU

之后单独买了一块RTX 5070 12GB ASUS的显卡，原价550刀，加税580刀。安装起来很顺利，从主机上卸下两块钢板用来接显卡输出，将显卡对准主板上的PCIE插槽插入即可。最后把视频信号输出换到显卡上面，主板和Win11系统都能自动识别显卡。补一个显卡驱动，装上CUDA，GPU的程序也能跑了。
这样总成本是1435刀，和一开始的预期差不多。

## Hardware for coding

Here is a [post](https://biojulia.net/post/hardware/) from BioJulia for scientists on how to write nice codes given the knowledge of computer hardwares. Very nice. Real workers know their tools.
