---
title: BU篮球半年记
date: "2024-07-07"
categories: [sports]
date-modified: "2024-07-17"
---

来BU打球半年有余，从一开始的不太适应到现在持续地和各种水平的选手过招，见识了不少人，也见证了自己的成长。常来的球友不少，偶尔光顾的众多，不断地观看和切磋，为了自己热爱的运动挥洒汗水。

## 对手印象

- BU华人球队的教练：他的力量略强于我，速度略逊于我。防守时喜欢对位协防人，体能的原因喜欢偷懒；进攻端持球核心打法，传球威胁很大，投篮能力强于BU华人球队所有队员，大概传六投四的比例。他不好防，因为有篮不能放太远，运球不追求速度但是节奏感很好，上篮慢悠悠的但低手上篮的手感不错。对位几次后，找到的最佳策略是逼他中距离急停跳投，受限于身体素质，无论是绕掩护还是生突的爆发力都不够，空位流畅舒展的投篮动作受到挤压后变形命中率下降很多。

- BU华人球队控卫：个子矮，大约165.爆发力极好，跳起来能摸筐。投篮弧度极高，在比赛强度的无球跑位中有能力瞬间甩开对手完成动作，是该队外线第一人。传球手法到位，传五投五的比例。然而突破攻击篮筐的效率很低，无论运球再流畅、速度再出色，到了篮下总是会被干扰进而打铁。两方面原因，其一是力量对抗不足，容易失去平衡；其二是臂展和手臂力量不足，起球后容易失去对球的控制。

- BU华人球队新人锋线：182左右，臂展长，身体素质好。喜欢单手完成上篮。投篮有明显甩的动作，不好封盖，命中率不稳，喜欢尝试高难度。年轻气盛，喜欢顶有球单防，但是容易吃假动作和掩护。组织串联意愿很低。在我看来属于全面弱化版的启轩Steven。

- BU华人球队得分后卫：跟我差不多高，速度快，第一次跟他打球的时候连连感慨自己跟不上年轻人的步伐了。投篮姿势是推的，辅助手有发力，有点篮子但没那么准。快攻的时候展示过欧洲步十分惊艳。

- John Wong: 香港人，左撇子。他的投篮和一般人不同，落脚时习惯右脚在前左脚在后，但是接球投篮的命中率相当可观。空切嗅觉很好，也有点抛投，但是运球能力一般，只走左边，防守时只要贴着堵左边就能限制。面如死灰，球场上毫无情感波澜。

- Ryan: 左撇子白人，偷下能力非常强。上篮都是几乎脚不离地的低手舔篮，反篮也有两下子。三分神经刀，姿势不标准，出手点低但速度快。标准魔球打法，没有中距离。

- Brian：个子180，身体强壮的内线。进攻全凭三板斧：快下、定点三分、背转身跳投。下快攻跑得比后卫还快。包夹出球意愿不错，手法一般。各项指标中最突出的是体力，作为有着健美身材的选手非常难得。

- 白衣韩国哥：强，全方位的。投篮准，不能放；突破放左边，人家就是能顶着进来上篮；进攻有条理，不勉强；下快攻速度快，我都不一定追得上。

- 打过一次半场3V3的白人：那次周六早上全场前的3V3，是这半年打的强度最大的半场。对位的白人球员我完全防不住，扛着我的投篮导致我完全无法起跳，往里打的背身由于身体差距也是只能望洋兴叹。后来有个和我单挑过两局11分的白人，和这位哥们有些类似，但是没有远投，只用中距离和背打就连赢我两局。输的点在于省体力的三威胁投篮稳定性不足，也是敦促我加强该技术的动力。

- 只出现过一次的白人巨星：在BU球场见过的扣篮最轻松的球员。一米九几的外线，那天看到的时候根本没认真打，抢篮板一点儿不跳。仅一球，一个体前变向衔接三步扣篮，举球过框带曲臂，那些个黑人球员也少有能完成的。我一度认为是NCAA校队私自溜出来打野的。

- 出现过两次的2米白人：2米110公斤的外线球员。准，八成终结外线完成。有运球能力而没有速度，通过身体对抗和身高制造空间完成投篮。属于重型外线炮台。

- 双色鞋的黑人：没有直接对位过。进攻节奏极其出色，三分撤步跳投非常流畅，个人进攻技巧野球翘楚。根据我对位类似黑人球员的感觉，他们的核心力量都非常好，撞一下跟撞上墙似的。但大部分的此类球员都不喜欢传导球，所谓传球都是奔着助攻去的，缺乏整体性的打球思路。

- 半职业黑人：瘦高臂展长，见过三回。其貌不扬，但非常厉害，防守端的判断和下手准度出类拔萃。曾经在一场15分的比赛里完成两次转换球权的上篮切球和一次正面外线防守的生断快攻。进攻端的个人快攻终结能力很强。传球能力并没有体现。

- 白衣黑人：性格友善，上肢强壮，终结多在外线。喜欢撤步跳投，但是弧度不高，命中率有却不稳定。他抗住我对抗后的跳投终结基本全看自己手感。上次对位时不知是不是先练了力量，篮下手感糟糕一个没进。防我进攻时脚步有些跟不上。

- 暴躁黑人：老哥来得挺勤快，一周两三次。脾气非常暴躁，时常和人发生争执和口角。身体强壮，对位几乎所有防守者都有能力完成突破；上篮时收球的手臂如同螃蟹的钳子，跟哈登一样，犯规和加罚的概率很高。传球技巧和视野非常好，绝对的传球优先。弱电是投射，外线几乎没有威胁。他的传球能力是建立在强健的身体基础之上的，体格类似德隆威廉姆斯。

## 个人训练

我十分清楚自己参与篮球运动的短板：身体素质一般，缺乏对抗力量和吨位，运球意愿不足，高强度下动作稳定性不佳。具体反映到球场上，就是体能跟不上跑不动，防守内线吃力，运球稳定性差，比赛中投篮命中率下降。

不想通过增重的方式提高对抗的前提下，更倾向提高肌肉的密度和可持续性。篮球的对抗讲究的是抗击打性，即高频率小力量的输出；这点和拳击有异曲同工之处。一场比赛并非通过单独一次举重式的绝对力量爆发而获胜，而是反复持续的有氧无氧切换，寻找全局层面的最优解。观看高水平运动员的训练，极少有大重量的器械锻炼，倒是充满了各种小肌肉群的小重量、多组数训练。这是在认识自己身体条件的基础之上为了特定的运动目标找到合适训练项目的过程。

有了身体作为基础，才可能谈及其它技术层面的东西。目前所有的终结训练项目以及比赛中使用情况：

| 项目 | 比赛使用频率 | 说明 |
|------|---------|------|    
| 抛投 | 常用 | 大部分左手，右侧的左手抛投不稳定 |
| 左右勾手 | 常用 | 左手为主，原地对抗发力转身会有吃不住人的情况  |
| 低手上篮 | 常用 | 右侧突破也是左手居多 |
| 顺步挑篮 | 偶尔 | 有对抗命中率不高 |
| 正手反篮 | 常用 | 稳定 |
| 反手反篮 | 极少 | 因为两只手都是顺手，比赛几乎不用该动作 |
| 转身上篮 | 偶尔 | 行进间使用不够熟练 |
| 欧洲步上篮 | 极少 | 吃膝盖和腿部力量 |
| 体前绕球上篮 | 极少 | 对手部力量和大小有要求，很容易脱手 |
| 身后绕球上篮 | 无 | 训练偶尔练习 |
| 背身跳投 | 极少 | 练习的时间不短，比赛中使用极少，因为缺少有防守人的感觉，并且落地平衡难以保证，很容易摔倒。 |
| 背身转身挑篮 | 偶尔 | 我的右腰外侧转身up & under属于无师自通。然而完整的版本包括两侧共四个角度，有练过，但比赛中没有使用过。 |
| 三威胁跳投 | 偶尔 | 软肋，举球动作速率和正常投篮不同；近半年有所进步 |
| 中距离左右急停 | 极少 | 左侧脚步调整慢，右侧发力会着急 |
| 中距离正面急停 | 极少 | 练习稳定，但比赛中使用场景极少 |
| 中距离撤步跳投 | 极少 | 难度高，核心力量要求高 |
| 绕掩护急停 | 偶尔 | 对脚步有要求 |
| 三分定点 | 常用 | 主要得分手段，稳定性不断提升 |
| 三分接球投篮 | 常用 | 对传接球能力和脚步调整技术有要求，命中率不如定点 |
| 三分侧撤步 | 极少 | 难度高，命中率不稳定 |
| 三分后撤步 | 无 | 难度极高，也不常练习 |

整体上通过多次运球完成的终结效率都会下降，和克莱倒是有几分相像。个人常用动作里面三威胁的干拔是弱项，这个本该是最轻松的得分方式，反倒是我最不稳定的投篮技术。问题可能在于在做完低重心的原地晃动以后，举球抬重心出手的过程中下肢力量没有很好地传递到手上。一直在改进，取得了些许进步。另外一点，也是持续要提醒自己的一点，提高运球比重，增强运球对抗的信心。

热身套餐经过这些年的打磨，已经形成了固定套路。行进间抛投似乎是个缺失的部分，可以考虑把升级第四级的投篮变成抛投。一套下来从拉伸到抛投12球、中距离跳投6球连进、罚球10球、三分50球，目前需要大概40分钟。三分50球有记录的自投自抢最高命中率是58%。FIBA三分线和美国常见的高中线有一定差别，投FIBA线有时候还是会感觉力量欠缺。

篮球的个人技术十分琐碎，需要每个人自己根据需求不断打磨。而个人技术和团队意识又是两个截然不同的东西，很容易造成顾此失彼的问题。我关注到的近些年国内青少年篮球培训，全部都是个人技术训练，没有任何讲解和练习团队配合的部分。这样训练出来的少年，在类似路人王这种单挑比赛的加持下，会不会认为篮球更多是个个人项目而非团队项目？而在我看来，篮球的乐趣更多在于它的团队属性，这是个人体育项目所不能比拟的。在国内打球，许多孩子的技术挺不错，但是并不能称得上会打球，是因为对于场上空间和时间的理解太浅，全然在乎的只有运球的自身和唯一的防守者。然而大局观是个很玄乎的东西，更切实际的或许是移动意识的培养：要告诉球员，手里没球的时候同样可以制造威胁、做出贡献。

好想打比赛啊。