---
title: 瑞典游记
author: "Hongyang Zhou"
date: "2022-01-23"
categories: [travel]
date-modified: "2022-01-23"
---

## Uppsala

瑞典，北境上的富庶王国。第一次踏上欧洲的领土，竟然是飞越了大西洋，途径冰岛，来到了波罗的海之旁。
波士顿到雷克雅未克的航班上，邻座左边是个美国老太太，右边是个印度小哥。老太太和三个朋友计划到冰岛旅行一星期，一路上神采飞扬的样子。她是个妇产科的护士，特别热情而耐心地跟我俩唠嗑，那种与生俱来的亲切感让人觉得特别温馨。我小睡的时候座椅靠背一直是打直的，她在一旁轻轻敲我的胳膊，告诉我可以试着把靠背放下去一点，说罢还自嘲老是像个母亲般唠叨。我跟她说我第一次出来开会，要做个海报展示，她听后连忙鼓励我说一定没问题，生怕我紧张。这些自然的反应，真是慈爱的天性。右手侧靠窗的印度博士，在斯德哥尔摩当生物研究员，刚在波士顿开完一周会，坐飞机赶回瑞典的家里：一位当药剂师的妻子和两岁的女儿在等他。他说早年很幸运到意大利交换，然后又在瑞典完成了博士学位，之后就选择在瑞典继续工作了下来。他恰巧和我完全同一趟航班，飞机到达冰岛又晚点了一小时，下趟的起飞时间有些赶，于是就有了我俩一路小跑带插队的入境找登机口的经历。奋斗在海外的印度人，跟我们中国人是多么相像。下飞机的时候，老太太在后面连声吆喝：“有人要赶飞机啦，麻烦前面的各位让一让！”看我俩往前挤到几乎看不见，又补上一句“祝你们好运”。到了登机口，平抚了下呼吸，印度小哥不禁赞叹怎么会有这么友善的女士。是啊，这么美妙的事。
到达瑞典是清晨，小雨初霁，大地如新。坐着火车18分钟就到了Uppsala，路上广袤的草场，时不时的牛群和马群，还在个桥洞口见识到了一辆真正的马车。凭着手机仅剩的10%的电，辨识着不认识的瑞典文字，八点摸到了下榻的酒店。来的太早，先前的房客还没退房，空屋子都没收拾出来。俊朗的瑞典哥们大手一挥：“咱这儿有早点，坐着喝杯咖啡上上网，过一阵再来问。”饿了一晚上饥肠辘辘的我，就这么厚脸皮地吃起了瑞典宾馆里的丰盛早餐。
单人间着实小，却是什么都不缺。困顿的我倒头就睡，醒来已是周日的下午五点半。窗外的这阳光灿烂得，就像三四点的安娜堡。出去逛逛，补上一餐。这20万人的小城，走出去十分钟就让我碰上一间写着中文的中国餐馆。服务生一听就是个北京口音，坐下思忖半天点上一盘孜然牛肉和一份蛋炒面，那滋味比之国内都不逞多让。

为什么我觉得乌普萨拉如此亲切？可能是Hannes Alfvén的缘故。这位等离子体届迄今为止唯一的诺贝尔奖获得者，就是在这里学艺成长的。从镇上一路走到学校，跨过车站，越过小河，有种林间漫步的童话感。学校在山上，而小镇在山下，这种层次感很容易产生高山仰止之意。

MOP外磁层会议期间的一天晚上，在我们白天开会的阶梯教室里有一场面向公众的科普论坛。瑞典民众的科学素养之高令我叹服，问出的问题都是基于基本理性和逻辑思考的。Fran的耐心解答和手舞足蹈般的演示也让我看到业内顶级科学家把复杂问题简单化的功力。讲解木星的电流片时，那个经典的芭蕾舞裙䙓动作令我印象深刻。作为行业内的女性科学家三巨头之一，Fran在两年后得到了AGU的终身成就奖，也是当之无愧。

周四的晚上，在城堡里举行的晚宴。这是我第一次切身走近欧洲的古堡，作为曾经乌普萨拉领主俯瞰领地的至高点，真有一览众山小之感。毕竟是我第一次参加学术会议的晚宴，在城堡门口等待的时候我既兴奋又紧张。在楼梯间便开始供应香槟，可能是酒会的常规开胃酒。进入正厅，五排长桌依次排开，嘉宾们依序入座，服务员列着队入场，为宾客们收起香槟的小高脚杯，斟起白葡萄酒并端来了前菜。大概记得是海鲜配一些蔬菜，味道一般。换至主菜，又给每人配了一支新杯子，倒了红葡萄酒，配上牛排，本就不大的桌子上一时间已然摆满了各式玻璃杯。然而，这还没完，点心环节竟然还有类似XO一样的洋酒，让我对于Banquet大大增涨了见识。Camilla, Yash和我坐在一起，附近还有一位泰国女生和英国女生，这样有跨度的组合借着酒兴让交流变得更有意思。原来Yash毕业于印度一家私立的理工学校，外公曾是一州的省长，父母如今都在新加坡工作。他来到美国读航天工程硕士前曾经在印度的航空公司实习过，对公司里的摸鱼文化深恶痛绝。

Uppsala真就是一个很小的地方，估计从城市一头走到另一头也用不了一个小时。学校在山上，城镇在山脚下，还有条护城河一路延伸过来。教堂、市集、车站、居民区，分得很是清楚。每天从车站旁的酒店走到空间研究所，穿过车站广场，走过商业街，跨国河转角走入公园，然后沿着足球场旁山径的小道穿梭十分钟就到了大楼前；亦或者步履沉重的时候，坐着公交车盘旋上下，约莫十五分钟就能从车站直到楼前。这里的风貌总让人产生时空交隔的错觉，一瞬间你在十六世纪，下个瞬间又来到了二十一世纪。在芬兰博后期间遇到了Andreas，正是在这里学习、成长，如今又回到了那个地方。从各个角度Uppsala都称不上繁华，但四处都有着生机和活力。

会议周三的下午有个集体出游的活动，驱车半小时来到附近一处古代战争遗迹，但我瞧了半天也没看出什么大阵仗。Tamas他们这群老家伙们显然也不是奔着旅游来的，而是为了那鲜扎啤酒。彼时我还未能领会酒的重大意义：这世界三大饮品，咖啡、茶与酒，贯穿了多少的人生一世。

### MOP会议纪事

Yash的首次演讲，以及德国老学者完全听不懂的问题；

校外首次海报展示，以及贾老师“宿敌”的礼貌问候；

旁边一位做Titan研究的美国小哥。

## Stockholm

有幸参与一个在斯德哥尔摩举行的有关波动的系列讲座，同时第一次踏进世界名城斯德哥尔摩。关于这座城市，我知道些什么？斯德哥尔摩综合征、诺贝尔奖、北欧最大城市、寥寥几点。疫情一波一波，斯德哥尔摩却几乎一切如常。

在各种层次上，斯德哥尔摩都是一座大城市：发达的公共交通，百万加的人口，标志性的建筑群，享誉世界的学府。在赫尔辛基待了一年走进斯德哥尔摩，如我所料般，想是走入了一个大号的赫尔辛基。然而瑞典王国的历史更加悠长，祖上阔过，两次世界大战也几乎没有波及瑞典领土，所以有众多流传至今的古迹。查了下资料才知道，我原先对于瑞典高校的认知存在一些偏差。各大榜单上瑞典的头牌都是一所坐落于城市西北角的医学院，其次是一所不在斯德哥尔摩反倒是紧挨着哥本哈根的学校Lund；我很早就知道的KTH排名上还不及Uppsala大学和Stockholm大学，但是在城市北边占了很大一块地，地铁站中唯一一个瑞典语的大学，指的就是KTH。

斯德哥尔摩有一些微妙的不协调感。我在城市里穿梭了三天，发觉了些蛛丝马迹：虽然公路交通遵循右行规则，但是地铁却是左行的；虽然瑞典人的英文普遍非常好，但是街上的标识几乎看不见英文。

绕着老城走了一圈，暗夜寒风，果然还是把我吹病了。疫情下的这个时间游客很少，但大多的纪念品商店、餐厅和酒吧依旧开着门。很遗憾没有时间去参观这数量众多的博物馆，但匆匆扫一眼便知这是我一定会专程再来旅游的地方。

### Nordita Winter School

讲座主办方Nordita坚持办了一个线下的讲座，我也没做多想跨过一湾海峡来到了瑞典。Nordita是一个理论物理研究所，由北欧国家共同资助。十几年前的时候Nordita还在哥本哈根，后来才搬到了斯德哥尔摩。这主要是个研究机构，只有很少的博士生，其余都是各个理论物理方向的博后和研究员。他们一直挂靠在Stockholm University的校园里，去年搬进了新的办公楼，占了整整两层，还有很多空阔的地方。玻璃隔间的办公室，宽敞的公共休息区，四处摆弄的拼图和小玩具，以及几乎每一面墙上都有的白板。这些白板可不是摆设，我目之所及上面都写满了公式推导，一看即知是真的在讨论理论问题的，而非敷衍忽悠大众的。如果说妙笔能够生花，那么现如今的数理研究工作就更应该像这样让人们能自由地探索思想。交流和碰撞，我很好奇有多少发现是在横的纸上做出的，又有多少是在竖的板上完成的。

在由于疫情取消了去年的冬季讲座后，今年他们坚持办了一个线下的讲座，请到了来自CMU天文系的Tina教授来讲重力波，和来自MIT核工程系Nuno副教授来讲磁流体波动。Nuno说是来讲波动，讲着讲着决定把话题扯到不可压磁流体理论中的湍流和磁重联，虽不是我直接来的目的，但也是打开了一类研究的新窗口。

每天午餐都在学校的餐厅吃自助，我感觉瑞典比芬兰懂美食，但是这各式混杂东西混搭，一度让我以为真是相当国际化的食物。
Nordita周三办了个特邀晚宴，是个很标准的西式晚餐，就在平日吃午餐的地方。学校新开不久的餐厅，Nordita身先士卒来包场，订了四桌二十人。前菜主菜甜品，意料之外的好吃，尤其那份甜点，是画龙点睛的一笔。每桌准备了一瓶白葡萄酒一瓶红葡萄酒，我们从七点一路吃到十点打洋，在几位东道主老学者的带领下几乎喝空了瓶。他们也是好久没有这样一群人坐下来畅饮聊天了，所以无论是所长、首席研究员Yxel，资深学者Dubra，还是Tina，比这帮前来的年轻学生们兴致更高。Nuno显然是最克制的那个人，比较安静，也没留到最后就先走了。学术界也有各式各样的人，Nuno可能更接近我原先想象的科学家的样子吧。

### 中餐

这里的中餐馆并没有我想象般多，选择余地跟北美大城市相比也少了个量级，但几天下来还是有些发现。除了周三的晚宴，其余每晚我都找了家中餐馆，借着公款吃喝的名头，一个人点两道菜。头天下午刚到，没吃午饭，在酒店附近瞅到一家亚洲馆子，我一开始以为是韩餐或是日料、结果是个东北大妈开的店——回头一看，店名是个“白马”的拼音。要了份炒面，好家伙，份量惊人，让我一度担心吃完晚饭是否都能省了。结果到了晚上还是坚持出去觅食，对比下就近选了附近居民区里的东北馆子。店名带“羊”，我想着定是主打羊肉，于是点了小葱拌豆腐和孜然羊肉。夫妻店加上女儿做些瑞典语翻译，聊了阵后才得知他们为了移民才举家出来，如今不过在瑞典待了三年，标准的新移民。瑞典的移民政策最近在收紧，但是相比其他国家依旧非常宽松，到了工作年限以后甚至连语言要求都没有。他们一家有亲戚在纽约，本来想着先去美国看看，结果办旅游签的时候直接被领馆以“有移民倾向”为由拒了。最终辗转来了瑞典，言语中仍透露出摆脱国内阶层固化的渴望和面对外国异类眼光的担忧。聊得虽开心，但这菜式出品一个比一个咸，结果老板娘跟我解释道瑞典人有时候吃这些个还要蘸酱油，我真是目瞪口呆——纯粹只是他们自己家口重罢了。吃罢小葱拌豆腐得到的经验，就是豆腐和葱为表，而里则是盐加味精。
第二个晚上的乡月餐厅正好在Stockholm University和酒店之间，傍晚结束讨论后就徒步走到了餐馆。一个不太常见的搭配蒜泥茄子，和一份别出心裁的将糖醋汁凝结成糖衣裹成的糖醋排骨，免费续的白饭，吃得有点撑；也亏我还能走回酒店。
第三个晚上在城市另一头的川菜小窝Little China，当之无愧本周中餐最佳。川北凉粉加牛肉面，非常地道，价格公允。与我年纪相近的夫妻俩在台前，两位身着统一厨师服的师傅在幕后，餐厅并不显眼，味道却着实令人惊喜。旁边两步路有一家华为的售后服务门店，想必他们也会时常光顾这里吧。
第五晚，在车站旁做完抗原检测，跨过桥向西来到香港餐厅。老板娘和服务员一看都是广东人，可菜单上却未必看得出来——也不知何时香港做起了北京烤鸭？通篇看下来并没有找到一眼能认出的广东料理，索性点了份拼盘咖喱饭，但也着实不便宜。老板娘想催命似的在我跟前晃来晃去，仿佛生怕我不点菜跑了一样。
第六晚，结束全部课程后来到老城区逛逛，在旅游经典附近找到一家号称从1968年开到现在的中餐Formosa。不查不知道，这个词来源于葡萄牙语，本意是“美丽”的意思，十六世纪葡萄牙人航海前往日本途中发现了台湾，船员惊呼“福尔摩沙”，于是大航海时代的欧洲习惯称呼台湾为Formosa。由此，这家店祖上肯定是台湾一代的，也难怪菜单里会出现温州拌面这道我在国内没去过温州就没听过的菜式。这拌面就是醋、蒜和面，一点都不好吃；毛家红烧肉做得倒是中规中矩，配的三份佐菜黑木耳、腌萝卜和花生米倒是十分出彩。
