---
title: Gravity Wave
author: "Hongyang Zhou"
date: "2022-01-10"
categories: [math]
date-modified: "2022-01-12"
---

> Make analogies of what you don't know to what you know.

## Questions

* What is a gravity wave?

* How can we observe gravity waves?

* Why is it important?

## Basic Math Tools

[Einstein notation](https://en.wikipedia.org/wiki/Einstein_notation)

[Covariance and contravariance of vectors](https://en.wikipedia.org/wiki/Covariance_and_contravariance_of_vectors)

I found a series of Khan lectures on the maths related to Einstein notation. I should go through the basics before doing anything special, cuz you can only speak after you learn the language.

There is a simple [example](https://math.stackexchange.com/questions/666246/tensor-einstein-summation-notation) for superscript and subscript. A simple rule is that **subscripts represent row vectors and superscripts represent column vectors.** (This is **ONLY** true for Euclidean space.)

[A Complete Guide to The Ricci Tensor](https://profoundphysics.com/the-ricci-tensor/).

Riemann geometry

##

Take a look at [electromagnetic tensor](https://en.wikipedia.org/wiki/Electromagnetic_tensor). The Maxwell's equations can be derived from from the Lagrangian formulation. 

##

Degree of freedom:

* symmetry of 3x3 tensor --> 6
* traceless: $g_{ii} = 0$ --> 5


### Dimensional Analysis

## Physics

### Comparison With Electromagnetic Waves

### Cosmic Microwave Background

[Cosmic microwave background](https://en.wikipedia.org/wiki/Cosmic_microwave_background).

### More questions

* [Do photons have energy?](https://physics.stackexchange.com/questions/59456/the-temperature-of-photon-and-its-energy)

* [E and B modes w.r.t. polarization](http://background.uchicago.edu/~whu/intermediate/polarization/polar5.html) and [their naming origin](https://physics.stackexchange.com/questions/104025/what-do-the-names-e-mode-and-b-mode-mean-where-do-they-come-from).

* Scalar, vector, and tensor modes in gravitational waves? Here is a related [paper of simulations](https://arxiv.org/pdf/2103.01140.pdf).
