---
title: 麦迪逊游记
subtitle: 比赛，亦或旅游
author: "Hongyang Zhou"
date: "2019-04-01"
categories: [travel]
---

Madison离Ann Arbor不近也不远，六个多小时车程，除了在Chicago恼人的堵车之外，其他的行程还是惬意的。我原以为她就在密歇根湖边，实际上在湖边的是密尔沃基，而麦迪逊坐落于密尔沃基正西约一个半小时车程的地方。她市里面有两个湖，大到曾让我看着地图以为是五大湖。UW的校园正处于两湖之间，一片空阔，风景绝美的地方。相比于安村，他们还是Wisconsin州的首府，所以商业气息更加浓郁：到了周末的晚上，成群的行人、游窜的酒鬼、时不时的音乐和喧嚣，显示出城市的一抹温情。Downtown中就有一家Kongfu Tea，墙上贴满了各式各样的便利贴，奇奇怪怪的内容和小广告，就快成美帝留学移民一条龙了。和往常一样，我们并没有住在离学校近的地方，比赛主办方找了家合作酒店，就是图个便宜。一起下榻的还有其他两三支球队，早上一起吃早餐的情景，也是似曾相识。Harry在周六晚上还到我们的酒店走访了一趟，我们一车人找了个借口故意躲开了，可想而知不得人心这事儿早不是一天两天了。

麦迪逊的体育也很好，篮球橄榄球都和密歇根有的一拼。可是他们这橄榄球场，相比于密歇根的Big House来说，略显寒碜了些。在橄榄球场旁边有一个室内田径场，
只是400米跑道中间的不是足球场，而是四个篮球场。如果说整个学校加起来就这么点运动场地，还是显得单薄了一点。不过我忽然想起来第一天晚上刚到的时候伟煜的同学
和我们一起吃饭前刚打完羽毛球，可那个室内运动场并没有羽毛球场，所以由此推断应该还有其他的运动场。周六中午我们在体育馆外寒风凌烈地吃着Burrito，我在他们学校
的体育纪念墙前看了好久，一个个扫过那些镀了金的名字，体味着Big Ten联盟中的悠久底蕴。将体育变成文化的一部分，欧美做得非常好。

我们初到的时候，在学校附近的一处小湖边散了会儿步。威斯康辛的僻静，在这傍晚宁静的湖水边一览无余。当年差了一点就来了这里，仅凭这一点也感觉有些亲切。比赛么没什么好说的，一顿操作猛如虎，该赢的赢了一场，该输的也都输了，马奎特大学的一个接近两米的大哥个人能力冠绝整个比赛，可惜队友实在不太给力；UIUC的八人组着实很强，他们是明显的实战派，平时的训练就是一起打野球，走的就是时下流行的炮轰路线。输给他们心悦诚服，队里的女生球技也比我们队中的一些男生要强。去年他们能拿下野狼杯的冠军，实力无需置疑。

之前跟冠儒以及炜煜的女朋友草莓姐都不是很熟，这一路聊过来也知晓了不少有意思的事情。冠儒原来在沈阳的外国语学习日语，从小走的就是不一般的道路，还有过在芝加哥home stay的经历；草莓姐给我们讲湾区的生活和见闻，以及为什么不愿意再回到五大湖区生活的原因。我们谈论教育，谈论家庭，谈论孩子，骤然觉得这趟旅行很值，有了一些未曾相见的际遇。

回来的路上经过芝加哥的一家日本超市，看到了许多平日少见的日本产品。在经过零食区的时候，冠儒向我们一一推荐了好吃的东西，最后提到了日本近些年还有个Pocky Day，是年轻情侣们借着一款叫Pocky的甜食来一起度过的情人节。我也是在这里第一次见识了M Lady，了解了这时尚前沿的蛋糕品牌如何打动了中国女生的心。当然还有芝加哥唐人街的撸串儿，这辈子吃过的最贵的烧烤，而且竟然还觉得没有饱腹。队友们忽地染上了修图瘾，虽然这次只拿了第四，但团队的氛围很好，为今后的进步奠定了基础。
