---
title: Des Moines之行
subtitle: GEM二刷
author: "Hongyang Zhou"
date: "2025-06-29"
categories: [travel]
---


今年的GEM和CEDAR合并了，在Iowa的首府Des Moines举办。NSF的资金比较紧张，合办能省不少钱。

首先从Des Moines的发音讲起。这名字一看就不是英语名字，发音时s都被吞掉了，记为/dəˈmɔɪn/。据说城市名源于法语，因流经城市的河流"Rivière des Moines"译做僧侣之河而得名。美国第81大城市，人口不到30万，大农村州政府所在地。第一次来到Iowa，我对Des Moines的城镇规划刮目相看。市里一条河流将城镇作东西两岸，东岸州金顶议会大厦盘踞于地势最高点，四下各式建筑错落有致，新房迭起；西岸市中心办公区，主体建成于50年前至20年前，人烟稀少，但空中连廊遍布，干净整洁，显然是精心设计打理的。河流两岸草地平整，轮滑公园到了晚上热闹非凡。市内支柱产业是保险、农业设备和物流，相关从业人员占据了1/4人口。

从酒店去机场的路上和Uber司机小哥聊天，他说他们家2018年从加州搬过来定居。他的孩子们喜欢雪，爱荷华四季分明，他们一家很喜欢。查了一下，最冷的一月平均气温-5摄氏度，最热的七月平均气温24摄氏度，每日相对湿度70%左右，各方面都很平衡。

Iowa近些年的人口增长主要来自外来移民，而其中的亚洲移民约占40%，主要来自越南、中国和印度。这一点从市中心的饮食就能看出来，越南粉店不少，越南超市也很近。酒店河对岸有个Asian Garden，实则是中华文化园，有一个牌坊，十二生肖的石刻，刻着“诚信”、“友善”等等传统美德的巨石，以及仿江南水乡庭院的木板桥。习大大四十年前曾经到访爱荷华考察农业，2012年的时候访美又专程回访，也让爱荷华和中国间建立起了一层特殊的缘分。爱荷华是美国农业重镇，产量和出口量均列全美第一，美国粮仓之名毫不为过。从空中俯视，这里土地广袤、沃野千里，自然条件得天独厚，也难怪农业如此发达。

我们的会场位于城市河流西岸的东北角，一旁连接着篮球、室内足球和冰球的体育馆，另一侧经由希尔顿酒店从空中连廊对接其它的高楼建筑。会场内并无吃饭的地方，每日午晚均需徒步行至南部寻觅食物。开了四天会后于会场的宴会厅里举行了晚宴，和去年的GEM相差不大，但有意思的是期间进行了一个CEDAR-GEM问答对抗赛，由在场的400名科学工作者现场扫码回答7个单选问题，包括你认为最成功的太空计划，你印象最深刻的仰望天空是看到的东西，你在何时准备报告，以及你来开会的目的等等。大家的反应还算热烈，而我更好奇在这样一群人中的认知是否相同。诸如最成功的太空计划，毫无疑问第一名是Voyager，但我非常惊讶MMS竟然能排在第二名。恰巧周四中午还和Brian在讨论这个，我们聊到空调的发明是由于纽约的报社需要在印刷报纸之后保持室内干燥，低因咖啡的发明是由于从非洲运输咖啡豆的船舱里漏水，人们发现海水浸泡下咖啡因竟然被稀释了。这些有意思的东西，包括爱荷华空间科学最出名的Van Allen发现的辐射带，都是带着许多意外色彩的。MMS最大的意外发现是什么？是唯电子重联。我感觉这个旗舰项目最大的成就在于工程，把所有仪器的精度都提高了一个量级以上，并且验证了多卫星重构三维结构的可行性。MMS能排在CLUSTER和诸多其它项目之上，在于群体的视角、当下和过往、以及未来的选择。

周五虽然还有报告，但我毅然决定出去转转。照着地图扫了一遍，圈定了三个地点：Iowa History Museum，Iowa State Capital，以及Science Center of Iowa。爱荷华的历史也没太多复杂的成分，就是印第安原住民和外来欧洲移民的角力，近现代工农业的发展，美国内战的影响，再到现代军事和电影产业。这座历史博物馆不大，但外形红墙交错，我很喜欢。一楼大厅很空，一侧摆放着由于市里保险公司盖楼从地下挖掘出来的猛犸象骨骼，另一侧挂着当年911事件美国人民和被塔利班劫持的4架飞机之间的奋战。从博物馆出来，沿着山坡的台阶一路向上，就走到了爱荷华议会大楼。这是一座宫殿式的建筑，中间的金顶尤其醒目，内部装饰一股浓厚的罗马风格，大理石的基底，金灿灿的中庭，大气恢弘。一楼左右两侧都是正在使用的政府办公场所，秘书室、州长办公室、小法庭。州长办公室门口摆放着她生平履历，一路从早年的校园篮球队到后来从军从政，以及一路获得的奖章勋章。参众两院的议事厅分立二楼两侧，中央各自摆放着林肯、华盛顿以及当今总统的画像。据说爱荷华是美国唯一把总统像摆放在中间的州。介绍的导游是位声音洪亮的大叔，热情洋溢地讲解着日常议会发生的事情，甚至于高中生为了修学分在参议院里面端茶送水取文件做作业也有提及。二楼中央是一间图书馆，高十余米，非常靓丽恢弘，经典的绿罩灯、螺旋楼梯，可惜如今仅保留了一个壳，已无人在其中修订阅读。从三楼的暗门可以踏上92级台阶到达金顶之下，道路狭小仅容一人通过，在上面人人讲话可以声如洪钟。往下一望，各层地砖纹路迥异，目光直抵一楼，如同近50米深井，令人心头一悸。从窗口向外望去，正前方呈现的是Des Moines中心全景。令人困惑的是门口三座大炮正对山下，走进一看是美西战争时缴获的战利品，不知为何被带到了爱荷华的首府。仅此一处，已让我觉得不虚此行。

下午吃过午饭后，步行10分钟来到科技馆参观。这里门票17刀，我满怀期待内有乾坤，进入后只觉差强人意。楼道里满是孩子们的喧闹声，大人们几乎无一例外都是陪孩子来的，除了我和组里同事俩闲杂人等。一楼有个乐高中心，哈利法塔、金门大桥、胡佛大坝、埃及金字塔、罗马斗兽场、以及这座科学中心本身，不知是哪些位神人的作品，都不是一般乐高门店里能找到的。旁边一个小朋友的动手乐园，搭电路、做帆船、钻木头、切树桩，如果是小朋友来肯定很兴奋。美国家长也是心大，小学生拿起锯子和电钻挥舞也不带担心的。小时候我也曾经拥有一个科学实验箱，包括声、光、力、电的各色小实验。啥也没特明白，就是学会了自己接电池弄个点灯，躲在被窝里照亮Game Boy打游戏。设想，如果那时候有个科技馆可以让我上手来折腾，我也会非常开心吧。另一侧有个小剧场，一个大学生模样的男生周围站着一圈小朋友，我们半程进去只听见些火焰、辐射之类的词语，也不知多少小脑袋真的在听。楼上三个馆，一个户外馆摆了些当地的动物，包括猫头鹰和蝙蝠的标本和几条活的响尾蛇。一个天气预报演播室，背后一片绿幕，据说每周五真的会有电视台的人来现场拍摄。第二个力学馆，全是互动道具，压力炮、弹力球、齿轮组、一排单摆、一块自制火箭发射台、还有风力驱动的轨道球。其中一台仪器是个大型吹风机，对着天上吹，把塑料球放在中间能在一段时间内保持平衡，利用的是400年前发现的经典的伯努利原理。然而玩儿的过程中我发现，不是所有的初始条件都能让小球抵达平衡点，并且经过一段时间，这种平衡都会被打破。如今的计算机仿真，能否完美重现这些现实中的物理过程？最后一个厅是天文馆，一片巨大的椭圆形巨幕，自选节目，播放的内容从星云到极光，就是朴实无华的视觉震撼。后面的互动展示也还成，微软Kinect捕捉的手搓黑洞，可见光、紫外、和X光频段下的太阳影像，还能让我学点新东西。毫无意外的，三人举起美国第一课人造卫星火箭模型的照片和样品模型陈列在关门口最醒目的位置，内部Van Allen设计的粒子载荷电路还清晰可见。没来爱荷华之前，我是真不了解Van Allen当年一直在University of Iowa工作。现在想想，他的传奇也带来了这所大学空间物理系半个多世纪的繁荣。爱荷华大学位于Iowa City,距离Des Moines一个半小时车程，也是座漂亮精巧的大学城。学校的设施远比我想象得现代化，再次体现出这里的人们在悉心经营着自己工作生活的地方。

从科技馆里出来已是三点。依体量而言，17刀的门票略显昂贵；周五的下午，满是小朋友和他们的祖辈带来游玩嬉戏。但我还是觉得不亏：走过许许多多的科技馆，每一家都有自己的风格，这种体验感，是不可复制的。SCI刚好构成了爱荷华科技馆首字母的缩写，一个美妙的巧合，也可能预示着这里的人们始终带着对科学的向往。如果让我提一个建议，我会说，让农业单独作为一个展馆，才能体现出爱荷华相较于其他地方最与众不同的特色。

一趟旅行结束了，我很享受。科学的向往不为经费所扰，我们从事的工作不为挣钱而存在。向老师们请教，是件快乐的事。
