---
title: 任天堂大乱斗
subtitle: AGU
author: "Hongyang Zhou"
date: "2019-12-28"
categories: [game]
---

任天堂大乱斗是一款神奇的游戏。2018年底上市的Switch游戏，多达三位数的基础人物、地图场景和总时长28小时的游戏音乐；大小地图分列的单人模式；不同于以往的格斗模式创新——一款有野心，也有完成度的任天堂作品。

樱井政博，同时也是心之卡比系列的制作人，看得出在此次的大乱斗中融入了自己的诸多思考。本身乱斗模式对于动漫游戏玩家的吸引力就是极高，带来的第一个难点便是如何权衡人物的多样性的操作的简易性。这里所谓的创新并不意味彻底改变以往格斗游戏的“轻拳、重拳、跳跃、格挡、必杀”的基本思路，而是选择“砍”，充分利用Switch的已有键位，不再追求以复杂的组合键释放绝招。格斗游戏的另一个重点，是胜利机制。本作大胆地抛弃了血条系统，胜利的唯一条件是把对手击出场景地图。显而易见，樱井受到了龙珠里天下第一武道会规则的启发，去掉了10秒倒地而保留了出场规则，使得大乱斗立刻变得和以往的格斗游戏区别开来。血条简化为伤害百分比，受到伤害越高，被同样的招式击飞的距离就越远。与之相伴的是游戏对于空间概念的拓展：格斗再也不用仅仅限制于地面，对于空间的利用率比以往的格斗游戏高出很多。

那么，大乱斗是如何平衡娱乐向和竞技向的需求的呢？
1. 招式的华丽程度和伤害完全不成正比：即使是新手玩家也能很容易打出绚丽的招式，但未必能容易达成胜利条件；
2. 道具的创意：基于角色的道具使用，增加运气成分；
3. 场景的变化性，同样也是增加不确定性；
4. 画风的协调：可爱与帅气并存，且减少违和感。

对于细节的用心，游戏硬件机能能够实现的极限，他们的野心也体现在诸如马里奥的背带裤材质这样的地方。制作人对于每一个角色都拥有绝对的设计权，这是游戏博而不杂的前提。

每个月新玩儿十个游戏，这是樱井对于行业发展的把握。

---

我听说这款游戏已经有些时日，但前几天才真正上手体验了几把。游戏本身的制作无话可说，若要挑毛病，那只能说NDS的摇杆还需要进一步提高。
以上内容有参考Gamker攻壳的游戏点评。希望他们有朝一日能从评论走向实干，做出博采众长独树一帜的作品。

任何游戏和产品最终都躲不过面向对象的问题。如何满足市场的需求，采用何种方式，决定了怎么样的东西能够生存下来。二十年前的五笔输入法在国内是如此流行，而今却已无人问津，根源就在于速度上的收益远远不及上手难度。一款一开始并没有明显先进理念的产品，可能因为其不经意间的兼容性吸引了各式群体的目光，并以集体的智慧达成后来居上的态势。有心者在任何领域提出一种新想法，周全的考虑意味着不能仅仅盯着自己能看见的优势，也必须看出弊端，并权衡左右。
