---
title: 新加坡之行
subtitle: AOGS初体验
author: "Hongyang Zhou"
date: "2019-08-06"
categories: [travel]
---


这次出行似乎有点仓促，什么功课都没做就直接收拾行李上了飞机。可能对于语言没有障碍且大不到哪里去的地区没有什么心理负担吧。但我也真的心大，仿佛回到了几十年前人们出行的方式。飞机预计早上六点多降落，七点钟从机场出来，会场也不知道叫啥，酒店也不知道叫啥。会议的议程手册压根儿没看，指甲刀和临时寄物柜的英文也不知道怎么说。这2G网看来要带我走天下了。

飞机上也是一波三折，先是发现之前打球裂开过的指甲处又不明缘由地掉了一块，后来又发现睡着后眼镜不见了。我做梦的时候还想着这眼镜不见了可就糟了，谁料到还真的不见了。幸好它没有掉在走道上被踩了而是落在了座椅的夹缝里，要不然谁知道还会整出什么事。作为我做过的最长时间的单程飞机，15个小时，黑了一整个航程，难吃的联航飞机餐，在南海空域还有不少扰动，留点小波折也算是再加深一层印象。

时差的问题还没想过，希望身体这次争气点。走之前想要提交的工作还没完成，忙里偷闲看看能不能做一点。八点到了酒店，寄存了行李箱后径直杀到了会场，第一印象已然有点失望。这个会场跟楼下的商场直接相通，而且AOGS只包了一层，同时还有好几个其他的珠宝、邮票、地产展览在布置，给人的感觉非常地混乱。三天在会场下来就发现一个Juno的分会场坐满了人，其他的说实在乏善可陈。就会议而言，这次的惊喜在于看见国内云南天文台有人在做晶格玻尔兹曼（LBM），而且看起来无论理论还是技术实现上都非常复杂，值得花时间好好研究。汪毓明老师又消瘦了不少，但是报告非常出色，虽然英语口语没有那么好，但是思路清晰，条理分明，表意通畅。开个会，所有人来了，讲完就走，对别人的工作大都不感兴趣。开个会没有一个同学，寂寞应如是。真是羡慕汪老师和贾老师的关系。

新加坡好吃的很多，但不等于说什么都好吃。随意在酒店附近找的评分最高的中餐，干炒牛河，正宗粤菜惊世骇俗，非多年功力不能及。我在广东这么多年，做成这样的牛河也是非常少见。路边的蛋挞也是相当不错，热情的阿姨送的豆浆和芝士包也还行。周三晚上专程慕名而去的坐落于中国城的了凡，号称全世界最便宜的米其林一星餐厅，招牌油鸡饭只要5新币，那一勺豉汁和油鸡，入口难忘，名副其实。相比起来，酒店旁边的海南鸡餐厅做的咖喱鸡套餐4.2新币，差了至少一个档次；而IT硕士法学博士老板开的街边杂乱中餐，那碗牛肉面就一言难尽了。后来问了俊实，得知新加坡在90年代有过一批大裁员，于是诞生了不少高学历的出租车司机和餐厅老板。诚如是。

新加坡的政治真的让人欣赏。今天看到一则关于某个电子支付平台广告一人扮演四大种族用户涉嫌侮辱华人的新闻，政府第一时间站了出来，强制要求撤下有违种族和谐的宣传，并且强烈谴责在公开媒体渠道进行的种族歧视。这个印度裔的政府官员面露愠色，直接道出政府“零容忍”的原则。新加坡到处有四种语言，多民族国际化程度非常高，而政府对于社会运行的责任更是当仁不让的态度，跟诸多西方国家形成鲜明反差。对比近日香港的动乱，同为城邦政治的新加坡，更令人刮目相看。
世界城邦国家的典范，新加坡当之无愧。这个历史仅能大略追溯到14世纪的国家，平静地经历了葡萄牙、荷兰和英国的殖民，在二战期间连同整个马来半岛沦陷于日本之手，二战结束后没多久便裹挟入席卷全球的反殖民浪潮，与马来西亚做了两年露水情人，最终还是在李光耀的人民行动党领导下脱离马来西亚城邦，成立了独立的港口国家。这个地方的人民和领导者们最精明的地方，在于时刻认清自身的现实处境、实事求是地寻找最优的发展路径。在统一的管理下，众多的难题都迎刃而解：住房、经济发展、工人阶级利益保障、城市规划、人口控制、以及国际合作。这是活生生的发生在弹丸之地的奇迹，东西方政治交汇下最令人瞩目的作品。无论是书本上、还是现实中，我都佩服得五体投地。

由出色的城镇规划衍生而来的，是新加坡世界领先的的建筑设计。走在市中心，总能看到一栋栋令人惊艳的空中楼阁，称一句巧夺天工绝不过分。为了适应热带的气候，在很多地方楼与楼之间都有梁桥连接，完全可以不晒到太阳通勤漫步。众多的购物中心都彼此相连，若是愿意的话在里面消磨一天都可以毫不在意。

作为运输业发达的代表，不光是船舶远洋运输，新加坡航空也已经蝉联了多年的世界综合评分第一。新加坡的空港飞机起飞频率，实测估计肯定小于1分钟。

返程飞机经过南海上空时，总能看见白色的点阵，我第一反应是海上的浮标。不过这显然经不起推敲，因为数量实在是太多了。同样的道理不可能是轮船，而经过排除，最有可能的物质是：垃圾。虽然不愿意相信，但这可能就是活生生的现实。只希望不是。

鉴于最近持续的香港游行活动，新加坡和香港之间的对比更加引起了我的兴趣。李光耀过世之际，三联曾经出过专题讲述新加坡的腾飞和今后的展望。
中国古话“治大国如烹小鲜”，但新加坡的城邦治理模式有多少能照搬多少需因地制宜，仍是千年学不完的课题。
