---
title: Biostation Retreat
author: "Hongyang Zhou"
date: "2019-09-15"
categories: [travel]
---

系里组织的第一次博士生的出游活动，一看是临近北密的学校的生物站，时间允许二话不说就去了。五年级的博士生只有我跟毅轩两人，其他都是些年轻的面孔。同届的学生估计大都很忙吧。作为系里五年来第一次的集体出游，真是要给研究生会的同学点个赞。

北密嘛，老地方了，连绵的森林、起伏的山丘、错落有致的风景。生物站坐落于湖边，阵阵妖风过境常有虎啸山林之感，夜晚临近天色骤暗，伸手不见五指。那种原始的和自然的亲近感，出没在消失的灯光里。湖上涟漪涌动，岸边停靠的小舟可以随取随划，硕大的湖面一眼忘不见对头。我们在林间穿梭，走下峡谷追随溪水的流向，直到估摸着午饭的时间才匆匆折返。美国同胞热爱徒步，此言不虚。到了下午，他们争先恐后跳入湖中，徐徐寒意根本不足为惧，唯有那种湖水与肌肤尖锐的触觉才能激发年轻的荷尔蒙。我已经老到脱不开午憩的程度，对于下水更是毫无兴趣。可能写几行代码才是更能刺激我的事情吧。
两晚的破冰行动（ice breaker）是出游的最大亮点。往事不堪回首，我漂洋过海四年，竟从来没有和美国同学有过这般非正式的交流互动。那些先入为主的概念，那些自以为是的矜持，全都是心里的小鬼在作祟。比如那个轮转一圈的你画我猜游戏，起初我以为凭我的绘画水平能成为众人的笑柄，甚至都动了缩在一旁观摩的念头，但实际参与下来才发现大家水平其实都差不多，就无非图个乐开心一下。另外的两个事实猜测游戏，真是陌生人社交里面的经典，参与其中才会意识到这种互动的卓有成效。中文、英文，其实不太重要，关键的是你敢说、会说。我要跨出这一步，建立自己的社交圈子。不怕出丑、敢于表现。
还是一些小细节更有意思。玩儿猜纸条上写的事实是关于谁的游戏时，我一下就听出来那个有关同性恋的故事是北大师弟写的，原因有二：他在游戏开始前主动提出能否更换纸条，因为他已经觉察出可能不妥；那种表达方式，太中国化。我完全能够理解他的尴尬之处，而他在承认之后的淡定解释也让我十分钦佩。那的确有点冷场，比如开头的Gay被变通的美国同学解释为Guy，也能体现出情商之高。Shannon是一路坐我车的美国胖妞，麻省人，非常和蔼健谈，年轻而有主见。她是新来的系主任Tujia的第一个学生，在Emory上了四年本科，偶然的机会和系主任想做的极光与机器学习研究一拍即合。我第一次和美国人谈论起中国的问题，中国和美国的差异，以及我眼中未来的发展方向。我们从纸质期刊聊到媒体站队，从言论控制聊到社会进程，那种表达的畅快感是前所未有的。我还成功得推销了一把Julia，人类努力的结晶应该有更多人来享受。Alan是大气那边的三年级，异常的活泼健谈，母亲是波多黎各人，开起玩笑信手拈来。Tim是我的室友，Gabor多年来招的第一个美国人，典型的Geek，Sheldon类型，smart is the new sexy.至今依然保持着早睡早起的规律作息，不顾旁人阻拦捧起一泓溪水一饮而尽，高中时就做过关于陶瓷超导的课题研究。Gabor会喜欢这个学生的，道不同不相为谋。Zach Butterfield 带我们去参观了他们组里做光合作用空气组分的野外观测塔，还舍身为我们示范了一下爬上近20米高台的英姿飒爽。Sarah作为整个活动的组织者尽心尽力，拿出了一个领导者应有的风范和担当。还有一个拥有奥地利美国双重国籍的Dan，一个曾参与大学冰球联赛的Dan，一个满口英式英语的芬兰小哥，Zach & Emily，扭伤了脚踝的小哥，也很Geek但有时也有点儿Creepy的小胖哥Chris，讲了个高中时科学小组的高尔夫发射器设计被Sarah说非常Chris的故事，Michael Jackson died on my birthday的金发美女小姐姐，热情开朗的Natasha，和活泼可爱的师妹樱潇……更不用说多年的好朋友毅轩，马上就要毕业了，以后去台湾一定找他。人有时会有惊人的记忆力，那种沉浸的快感令人陶醉。
师妹在回来的车上还问我该怎么提高英语，聊起来说她考过五次托福，申请之路也是一波三折。偶然机会才得知是兰州人，南京大学人才济济，我辈之中后生可畏。

除了我们之外，一群Rackham fellow的老教授们也在那里召开讨论班一类的活动。这个生物站已有110年历史，夜不闭户，wifi信号却异常地好。想象着那种在大自然的怀抱中科研的场景，就连写出来的代码，也应该更富诗意吧。
投我以木桃，报之以琼瑶。愿密大一直守护着这世间的美好。
