---
title: 墨西哥杂记
subtitle: 圣诞新年七日谈
author: "Hongyang Zhou"
date: "2018-01-01"
categories: [travel]
---

我把旅行中零散的记录收集在一起，再额外补充一些，作为17年墨西哥旅行的纪念。感谢泽哥、佳星和颖怡的同行，感谢热情的墨西哥人民。

据说墨西哥很多地方非常危险，犯罪率极高，美国官方都不建议作为旅行目的地。幸好，作为旅游胜地的坎昆和首都的墨西哥城，至少在我看来，并无危险。

坎昆的海滩有着绝美的风景，沙滩、海水和天空的层级感非常强烈。可我这个海边的孩子，对于这些的记忆已然足够丰富，于是便唤不起多少的惊奇。

圣诞夜，坎昆的餐厅多数关门歇业，当地的超市也在八点钟关门，找个晚饭变成了件不容易的事。庆幸的是，我们在一家酒吧旁边找到了一家还在营业的墨西哥餐厅。服务员很热情，即便连英语都不会说，仍然尝试着在谷歌翻译的帮助下通过肢体语言来和我们沟通。可就在这家如同街边排档般的餐厅里，我们找到了梦幻一般的美食：pozole，唇齿留香的墨西哥玉米肉汤。以玉米糠（hominy）为底，和猪肉、番茄一起熬制半日，加入鹰嘴豆，呈现鲜红的肉汤，那恰到好处的酸味刺激着味蕾，软糯的豆子和鲜嫩的猪肉一起，构成了一道完美的晚餐。比起tacos，这道无心插柳的美食让我重新认识了墨西哥菜。据说玉米是阿兹特克人民神圣的植物，所以这道玉米肉汤也是当地节日必不可少的菜品之一。
题外一句，UM的颜色是maize and blue，这黄色，就是玉米黄。

xplor, 一天的丛林探险体验，这辈子没穿鞋走的最长的路。高空的滑索、地下河的竹排、丛林的越野车，以及与鸟儿争食的自助食物。

chichen itza, 玛雅文化的分布之一，世界新七大奇迹之一。走在园区里，随着导游的讲解，你不得不佩服古玛雅工程师的天宫之巧：击掌回声的设计，密室里扩音器的结构，四面台阶与玛雅阴阳历法的对应关系，大金字塔内嵌小金子塔的轮回构思……同样的，那个竞技场的7/14次回声的设计，穿越孔环的球类竞技，也是令人倍感惊奇。传说中这里举行着类似今日世界杯一样的比赛，每队7人，胜者的队长会被败者取下头颅，达成献祭神明的光荣使命，而头骨会被摆入东侧的英灵冢。这种不可思议的文化传统，表征着古人对于自然的敬畏。刻在竞技场的图腾似乎印证着这个说法：一全副武装的力士左手提着头骨右手持剑，而另一侧一具无头人像单膝跪地，从颈部长出三头长蛇——羽化的蛇图腾，正是玛雅人憧憬的圣灵。

玛雅文明遍布于如今的北美五国，各自又有和而不同的发迹。chichen itza 存在的sinkhole，吸引了最早的一千玛雅人来此定居。很难想象这片丛林之中，竟然会存在天然的地下水坑和洞穴，给文明添上了一线生机。后来由于资源的用尽，玛雅人离开的曾经繁华的故土，散布于整个中美地带。传闻中玛雅的灭亡被部分人归因于殖民者的入侵，而导游作为玛雅人的后裔，倒是为西班牙人说了句话：当年玛雅以及阿兹特克的没落，大都不是由于殖民者主观的杀戮，而是他们无意中带来的瘟疫席卷了美洲。墨西哥人的这种历史态度，是我未曾预料而又敬畏有加的。

连着三天吃着路边的小摊，一侧是酒吧的重金属轰鸣，另一侧是墨西哥小哥灿烂的笑容。我完全听不懂西班牙语，他也几乎不懂英语，但是今晚我独自前去，却连谷歌翻译也不需要，凭着比划和猜测就能明白彼此的意思。我吃着猪肚汤，想象着把这家餐厅搬到国内的夜市上人潮如涌的场景。不过他们未必乐意把店开到异国他乡：坎昆是他们生活的地方，他们希望的不定是荣华财富，而更可能是平淡中的小幸福。至少对于我这个异国游客，能够在这里吃上三天的当地美食，我觉得三生有幸。我们穿越了游人如织的海景酒店，吃过海边的卷饼饮过龙舌兰，在我看来，却远不及那招手即停的飞奔的公交，以及这市井生活中通宵的小店。对面的购物广场，是现代化城市的标准配置；而如我走遍天涯，却只想见识各地实在的风景。不是摩登就意味着快乐，也不是繁荣就会带来享受，人们追求着所谓更好的物质，却离一颗安定娴静的心愈来愈远。
我无须碧海蓝天来疏解烦躁的心情，只希望在旅行中探索人性和生命的意义。如同那张印刻在脑海里墨西哥小哥的笑脸，这段记忆，日后定会被我一次次提起。

我愈发地享受着，在异国他乡，没有手机信号，充满语言障碍，远离日常的旅行。如果不逃离，你在哪里，都在那里。

墨西哥城西北370公里，5个小时的大巴车程，传说中的旅游胜地瓜纳华托。
这里没有COCO电影里那么浪漫，但是已然十分惊艳。建在山里的城镇，一级一级扶摇直上，层层叠叠，尤其是夜晚灯光亮起，如繁星点缀，闪烁夺目。大街小巷都飘荡着节日的歌声，在崎岖回绕的建筑里穿行。我们住的宾馆，就有四层三十多间房，分布极不规则，愈往上房间愈少。而白天的市镇呈现出不一样的繁华，到处都满是人群，集市里尤其热闹。这个城市因为银矿而兴，老城地下更是隧道遍布，密集得如同排水网。而历史上，这些隧道的确也起到过泄洪的作用：山间曾经洪水肆虐，故而山城房屋越盖越高，低洼处也早已被打通至别处。

墨西哥城亦是别具特色。对于一个中国人而言，来到另一个第三世界国家的人口密集的首都都是别样的经历。墨西哥城，正是个污染严重、交通拥挤、人口稠密、盛衰交杂的高原都市。她集中了全国五分之一的人口，承担了一半以上的贸易和经济活动，跟国内的密集人口地区非常相似。在城市中心区的步行街，每天早十点到晚十点都是人满为患，比之南京路是有过之而无不及。中心区大都是西班牙风格的建筑，白天街边都是商贩，金银首饰居多，而服装玩具电器也是交错其间。餐厅大都不在一楼，需要穿越街边的商贩从不起眼的狭窄入口进入，若非服务员带领则极难寻找。

在墨西哥，亚洲人绝对是稀有物种。颖怡和佳星一天内被三番五次地要求合影，珍奇的异国人也有了明星的感觉。
大晚上的步行街，ATM机前面竟然排起了长龙，不经让人疑惑墨西哥人究竟是如何逛街的。

不懂西班牙语，这种体验非常有趣。在宪法广场西侧寻找餐厅的时候，只朝天一指，估摸着餐厅的位置，就有路上的餐厅服务员说着西语过来给我们引路；点菜的时候常手舞足蹈，要一杯白水（agua）都能出现四五种可能。那日在面包店还看见了traditional agua，竟然是种紫色的布丁，让我们不禁猜测这个单词到底是个啥意思。

墨西哥的几个重要时间点：
* 13xx，Aztec王朝建立，历经七代；
* 1519，西班牙殖民入侵，Aztec王朝覆灭；
* 1810，在拿破仑战争席卷整个欧洲大陆期间，墨西哥宣布独立
* 1829，墨西哥建国，其后军事政变频发，独裁更迭频繁；
* 1846-1848，美墨战争，墨西哥割让得克萨斯、加利福尼亚和新墨西哥州；
* 1862，法国以“索债”为名，联合英国、西班牙军事入侵，奥地利大公被扶持为墨西哥皇帝；
* 1867，Benito Juárez（墨西哥民族英雄和领袖，身高146）赶走了法国侵略者，枪决傀儡皇帝；
* 1876-1910，Porfirio Díaz 独裁统治三十余年；
* 1916，现代资产阶级民主政府建立

Aztec的金字塔在宪法广场的东北方保存了一处遗址，遗骸处依稀可见当年王朝的恢宏建筑。历经二百年，七任帝王，金字塔就扩建了七次，正如同玛雅人金字塔随时间轮回的扩增。而里处金字塔上神庙的复原发现，当年此处其实矗立着两座神殿，如同日月调和、阴阳相济，代表墨西哥人对自然的认知。如今的国家大教堂围栏里也分了大小两座，不知道是否也是遥相呼应的手笔。

从墨西哥城中心的城堡Castillo de Chapultepec俯视整座城市，庞大、朦胧、现代与传统相融。公园中的人类历史馆讲述了美洲大陆的迁徙发展史，从亚洲跨越白令海峡到美洲，从玛雅到中墨西哥的Aztec。墨西哥是个多民族国家，她经历过封建、经历过殖民、经历过独裁，最后才过渡到民主，中北部的自然景象和东南部也全然迥异。历史上曾发生过不止一次的文明中断，而大面积的统一王朝直到14世纪才出现。看墨西哥的历史让我领悟了历史学的横向脉络，就像天体科学中的地质和大气研究一样：你会知道什么是生存的基本条件，什么是文明的基本要素，以及什么是繁荣延续的基本前提。而大类总是相通的：资源、文字、商业、科技。Aztec鼎盛的时期，是我国的明代——双方的实力对比，坦诚地说，不是一个级别。但是，文化的脉络、发展的轨迹，诸如此类的事物，却是惊人的相似。我遗憾地看到西班牙语遍布着整个拉丁美洲，说明在重要环节的缺失，会为社会的发展埋下严重的隐患。西班牙当年为了彻底征服Aztec王朝，把首都Tenochtitlan夷为平地，并且在神庙的遗址之上直接修建了教堂和宫殿。Castillo de Chapultepec屹立于墨西哥城内不多见的山丘之上，建于18世纪末，是西班牙总督的夏季行宫，原址就曾是阿兹台克建筑，后来成为西班牙修道院。我很好奇，墨西哥人民，尤其是Aztec的后代，是如何看待那段抹不去的殖民历史。

Telcel是墨西哥随处可见的电信公司，也是拉丁美洲最大的电信公司，我原本以为是国有企业。但联想到曾经的世界首富Carlos Slim是墨西哥的电信巨子，若是国有就很难自圆其说。果然在多年前的新闻中查证，他在90年代初墨西哥国企转型期间收购了Telmex，随后便依托电信业的发展建立了庞大的商业帝国。在墨西哥，你是躲不开他旗下的产业的：从电话网络、轮胎瓷砖，到电视餐饮。人们抨击他从垄断和独裁中得来的财富，也有墨西哥人愤怒地控诉在这篇贫富差距巨大的国土中竟然出现了世界首富。他工作的时候几乎不做慈善，人们抨击他；在后来做了部分慈善，人们说他伪善。事实上，树大招风，你做什么，都有人抨击你。我欣赏他的一句话：拯救贫穷不能靠做慈善，而应该依靠教育和就业。他还知道中国的古谚：授人以鱼，不如授人以渔。

据曾经生活在美国西海岸的朋友说，洛杉矶现在的第一大种族可能是墨西哥裔。室友去德州旅游归来，也说西语在休斯顿之类的地方要胜过英语。从美墨边境开车进入墨西哥检查极松，但入美国境却检查极严。川普曾说过要在美墨边境修一堵墙，来阻止墨西哥的偷渡者——不知道墨西哥的北部，是否代表着贫穷、混乱和毒品。

在墨西哥，无论是坎昆还是墨西哥城，巨头主导的景象还是清晰可见的。坎昆的旅游项目几乎都被XCaret包办了，出租车和巴士也是统一把持；墨西哥城大部分的出租都是一样的长相，长途汽车站的巴士公司两强相争，更别提OXXO和Telcel这类零售和电信巨头。这里的资本化程度并不低，在拉丁美洲更是仅次于巴西的第二大经济和教育中心。美国资本的渗透也是非常明显。

现金支付是当地大部分地区主要的方式，直到现在仍有大量居民不随身携带信用卡。网络支付发展缓慢，从我试图在线支付AeroMexico的选位费和长途巴士车费的屡次失败中就有切身体会。

玉米是墨西哥最主要的食物，tacos遍地。墨西哥离不开洋葱和香菜，以及各式辣椒酱组成的salsa。但这次，我发现墨西哥的饮食不止以前理解中的那般粗旷，炸鱼干、芒果布丁、玉米肉汤、bistec asando烤肉、腌仙人掌、烤猪蹄、甚至面包都做得有滋有味。

琐碎的感慨，离散的片段，浮光掠影，人世沉浮。

## 2021/02/23

中国人并不了解墨西哥。对于我们而言，墨西哥的形象深深伴随着美国的影视作品：毒枭、偷渡、黑帮，不是已经黑在美国就是在前往美国的路上。2020年，墨西哥可能是中美贸易战的最大受益者，对美出口贸易甚至超过了中国。墨西哥是目前世界第十五大工业国，汽车工业占比30%，然而产品多数在北美内销了，所以国人对其的熟悉程度甚至还不如孟加拉的毛衣。三年前我去的时候，切身体验就是和中国很像。然而比之中国，他们的工业品牌更加稀缺，种类也高度依赖美国的风向，所以备受掣肘。摆脱美国小弟的形象，发展本土独立品牌，将是墨西哥未来寻求的道路。

然而督工比我看得深刻的地方，就是找到为什么墨西哥没有在这么长的独立时间内建立本国完善的工业体系并晋升发达国家。落后国家为了建立现代化的工业体系，需要靠国家力量对本国产业进行补贴。比如苏联、中国在工业起步阶段都是靠农业倒贴工业，手段主要是关税和直接对企业发放补贴。然而墨西哥并不具备靠农业支持工业的条件，根源在于土改不彻底。于是墨西哥的方法是借外债。1982年外债危机爆发，这条路就被堵死了。对外，在资本主义国家进行自由贸易而没有太多的限制条件，并不是每个国家都能享受到的。在20世纪中后叶，能享受到单方面保护本国产业同时进行国际贸易的国家主要集中在苏联附近，都是靠政治上的牵制。而墨西哥位于北美洲，紧邻美国，倒向苏联阵营几乎不可能。墨西哥的地理位置，决定了她没得多余选择，只能在闭关锁国和彻底开放之间抉择；当遇到债务危机被迫开放的时候，墨西哥所有的工业企业无论是否准备好了，都必须暴露给全世界的竞争对手，所以墨西哥最终丧失了主导自身工业化的机会。几轮债务危机后，墨西哥的商业银行体系几乎全部外资化。北美自由贸易体系签署后，美国的廉价农产品大量涌入墨西哥，低效率的小农场快速破产，所以墨西哥的人均GDP停留在了一万美元的水平上，陷入了所谓的“中等收入陷阱”，在可期望的未来没有快速改善经济条件的机会。

我的个人经验是，墨西哥主食玉米，同时近些年大量种植牛油果。玉米她几乎不可能种得过美国，牛油果估计是倾举国之力推销的农产品。然而牛油果的种植需要的水量惊人，据传对土地干旱有明显的加速效应。牛油果就好比智利的樱桃，都是想靠一种招牌农产品打通国际贸易的敲门砖。
